// GENERATED by scripts/build.js — do not edit by hand.
// The run pool: every audio file in src/audio/music/, in name order. Track
// titles come from these filenames, so renaming a file renames the track.
window.MUSIC_TRACKS = [
  "audio/music/Atmospheric Drift.m4a",
  "audio/music/Current Surge.m4a",
  "audio/music/Cyber Sun.m4a",
  "audio/music/Dark Neon.m4a",
  "audio/music/Dont Blink.m4a",
  "audio/music/Drifter.m4a",
  "audio/music/Neon Dash.m4a",
  "audio/music/Night Run.m4a",
  "audio/music/Steel and Rain.m4a",
  "audio/music/Sub Level Three.m4a",
  "audio/music/Terminal Velocity.m4a"
];
