// Supabase Edge Function: sim-ids
// THE DEPLOYED BOARD IDS, READABLE WITHOUT A SESSION (Gil, 2026-10-01).
//
// submit-run already refuses a stale build per board ("client outdated", 409) —
// but it refuses AFTER the stage is flown, so the player learns on the END screen
// that the score they just earned will not post. This function lets the game ask
// at boot which board ids the live verifier carries, compare them with the ids
// stamped into its own bundle (window.__SIM_LEVELS), and mark a stale stage
// BEFORE the player deploys into it: UPDATE GAME TO POST SCORES.
//
//   client → GET (apikey only, no session)
//          → { simId, accepts, boards: { "cargo-run:6": "…", "weekly": "…" } }
//
// It is its own function, not a GET on submit-run, because submit-run sits behind
// verify_jwt and the publishable key is not a JWT: the only way through that gate
// is a user session, and minting one for every install at boot — for a player who
// may never post a score — is a cost and a footprint this read does not warrant.
// The ids are hashes of shipped code; there is nothing here to protect, and the
// answer is cached for five minutes at the edge.
//
// _ids.mjs is GENERATED by scripts/build-verifier.js from the SAME SIM_LEVELS it
// writes into submit-run/_sim.mjs, in the same run, and scripts/deploy-verifier.sh
// deploys both functions together. One truth, two readers — never a hand-kept
// version row that could disagree with the verifier.
import { SIM_ID, SIM_ACCEPT, SIM_LEVELS } from "./_ids.mjs";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
};
const json = (body: unknown, status = 200, extra: Record<string, string> = {}) =>
  new Response(JSON.stringify(body), { status, headers: { ...CORS, "Content-Type": "application/json", ...extra } });

Deno.serve((req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "GET") return json({ error: "GET only" }, 405);
  return json({ simId: SIM_ID, accepts: SIM_ACCEPT, boards: SIM_LEVELS }, 200, { "Cache-Control": "public, max-age=300" });
});
