#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, '..', 'src');
const assetDir = path.join(__dirname, '..', 'assets');

// Create src directory if it doesn't exist
if (!fs.existsSync(srcDir)) {
  fs.mkdirSync(srcDir, { recursive: true });
}

// ---------- soundtrack manifest ----------
// src/audio/music/ IS the run pool: drop an mp3 in, run the build, and it's in
// rotation. Titles are derived from the filename at runtime (see prettyTrackName
// in index.html), so renaming the file renames the track — there is no second
// place to keep in sync. The generated file is committed so a fresh clone (or a
// file:// open) plays without building first.
const MUSIC_EXT = /\.(mp3|m4a|ogg|wav)$/i;
const musicDir = path.join(srcDir, 'audio', 'music');
const tracks = fs.existsSync(musicDir)
  ? fs.readdirSync(musicDir).filter(f => MUSIC_EXT.test(f)).sort((a, b) => a.localeCompare(b))
  : [];
const out = `// GENERATED by scripts/build.js — do not edit by hand.
// The run pool: every audio file in src/audio/music/, in name order. Track
// titles come from these filenames, so renaming a file renames the track.
window.MUSIC_TRACKS = [
${tracks.map(f => '  ' + JSON.stringify('audio/music/' + f)).join(',\n')}
];
`;
const outPath = path.join(musicDir, 'tracks.js');
const prev = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : null;
if (prev !== out) fs.writeFileSync(outPath, out);
if (!tracks.length) console.warn('! no audio in src/audio/music/ — runs will have no soundtrack');

console.log('✓ Build directory ready');
console.log('✓ Assets available at', assetDir);
console.log('✓ Run pool: ' + tracks.length + ' track(s)' + (prev === out ? ' (unchanged)' : ' → src/audio/music/tracks.js'));
