#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, '..', 'src');
const assetDir = path.join(__dirname, '..', 'assets');

// Create src directory if it doesn't exist
if (!fs.existsSync(srcDir)) {
  fs.mkdirSync(srcDir, { recursive: true });
}

// ---------- soundtrack manifest ----------
// src/audio/music/ IS the run pool: drop an mp3 in, run the build, and it's in
// rotation. Titles are derived from the filename at runtime (see prettyTrackName
// in index.html), so renaming the file renames the track — there is no second
// place to keep in sync. The generated file is committed so a fresh clone (or a
// file:// open) plays without building first.
const MUSIC_EXT = /\.(mp3|m4a|ogg|wav)$/i;
const musicDir = path.join(srcDir, 'audio', 'music');
const tracks = fs.existsSync(musicDir)
  ? fs.readdirSync(musicDir).filter(f => MUSIC_EXT.test(f)).sort((a, b) => a.localeCompare(b))
  : [];
const out = `// GENERATED by scripts/build.js — do not edit by hand.
// The run pool: every audio file in src/audio/music/, in name order. Track
// titles come from these filenames, so renaming a file renames the track.
window.MUSIC_TRACKS = [
${tracks.map(f => '  ' + JSON.stringify('audio/music/' + f)).join(',\n')}
];
`;
const outPath = path.join(musicDir, 'tracks.js');
const prev = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : null;
if (prev !== out) fs.writeFileSync(outPath, out);
if (!tracks.length) console.warn('! no audio in src/audio/music/ — runs will have no soundtrack');

console.log('✓ Run pool: ' + tracks.length + ' track(s)' + (prev === out ? ' (unchanged)' : ' → src/audio/music/tracks.js'));

// ---------- STAGE dist/ — what actually ships ----------
// capacitor.config.json used to point webDir at src/ itself, so `cap sync` copied
// the RAW SOURCE TREE into the APK: 13.4MB of unreferenced character plates, a
// dead 2.7MB menu track, a .bak of the tunnel painter, and editor.html — a live
// dev source-viewer that was reachable inside the shipped app. 61.4MB of APK,
// about 16MB of it provably unreachable.
//
// This is a COPY WITH A DENYLIST, not a bundler. src/ is untouched, still 33
// <script src> tags, still opens at file://, still zero dependencies — everything
// docs/REFACTOR-PLAN.md section 5 protects. The only new fact is that there is now
// a staging directory between the source and the package.
const distDir = path.join(__dirname, '..', 'dist');
// Anything matched here never reaches a device. Each entry is here because it was
// verified to have zero references from the game (grep across src/ and scripts/).
const NEVER_SHIP = [
  'audio/Midnight_Terminal_Wait.mp3',  // 2.7MB — the previous menu take, replaced by 262be2d
  'editor.html', 'editor.js',          // the Lane Designer: a dev tool, not a game screen
  'game/manifest.json',                // build-time load order; nothing fetches it at runtime
  // THE BRAND MASTERS. src/icons/logo*.png are what the art is re-dropped as;
  // `npm run icons` converts them to the lossless webps the game actually loads
  // (src/logo.webp, src/logo-small.webp) and cuts the launcher set from them.
  // Shipping the PNGs too packaged 744KB of duplicate brand — the exact double
  // -copy scripts/icons.py warns about in its own docstring. The masters stay in
  // the repo (they are the thing to re-drop); they just never reach a device.
  // GB-logo-hollow.png is NOT here: 99-boot loads it as the studio mark.
  'icons/logo.png', 'icons/logo-small.png',
  'icons/gb-logo.png',                 // the solid studio mark — only the hollow one is loaded
  '.DS_Store',
];
const SKIP_EXT = /\.(bak|stale-bak|orig|rej|md)$/i; // .md: notes-to-authors, never a game asset
// `_`-prefixed files are fixtures — the disc test card, for one. They exist so the art
// pipeline can be re-verified against a known image; they are not content.
const SKIP_FIXTURE = /^_/;

function shipPath(rel) {
  if (SKIP_EXT.test(rel) || SKIP_FIXTURE.test(path.basename(rel))) return false;
  for (const deny of NEVER_SHIP) {
    if (rel === deny || rel.startsWith(deny + path.sep)) return false;
  }
  return path.basename(rel) !== '.DS_Store';
}

let copied = 0, skipped = 0, bytes = 0;
function stage(relDir) {
  const from = path.join(srcDir, relDir);
  for (const name of fs.readdirSync(from)) {
    const rel = relDir ? path.join(relDir, name) : name;
    const abs = path.join(srcDir, rel);
    if (!shipPath(rel)) { skipped++; continue; }
    const st = fs.statSync(abs);
    if (st.isDirectory()) { fs.mkdirSync(path.join(distDir, rel), { recursive: true }); stage(rel); continue; }
    const dest = path.join(distDir, rel);
    // mtime+size check, so a rebuild does not re-copy 40MB of audio every time
    let stale = true;
    try { const d = fs.statSync(dest); stale = d.size !== st.size || d.mtimeMs < st.mtimeMs; } catch (e) {}
    if (stale) { fs.mkdirSync(path.dirname(dest), { recursive: true }); fs.copyFileSync(abs, dest); copied++; }
    bytes += st.size;
  }
}
// prune anything in dist/ that no longer has a source (a renamed track would
// otherwise ship forever alongside its replacement)
function prune(relDir) {
  const here = path.join(distDir, relDir);
  if (!fs.existsSync(here)) return;
  for (const name of fs.readdirSync(here)) {
    const rel = relDir ? path.join(relDir, name) : name;
    const abs = path.join(distDir, rel);
    if (fs.statSync(abs).isDirectory()) { prune(rel); if (!fs.readdirSync(abs).length) fs.rmdirSync(abs); continue; }
    if (!fs.existsSync(path.join(srcDir, rel)) || !shipPath(rel)) { fs.unlinkSync(abs); }
  }
}
fs.mkdirSync(distDir, { recursive: true });
stage('');
prune('');

// ---- stamp the build's sim id into the shipped index.html ----
// The client has to be able to say WHICH rules it played by, or the server
// cannot tell a run made by an out-of-date app from a forged one — and it was
// calling the first the second, which reads to a player as an accusation.
// Stamped here rather than in src/ because the id is a hash of the game
// sources: a stamp inside them would change the hash it is recording. Served
// from src/ (the dev server) the value stays null, which means "unknown" and
// leaves the check off — dev builds are not trying to prove anything.
{
  const simId = require('./lib/sim-id.js').simId(path.join(__dirname, '..'));
  // …and the per-board behavioural ids, so a client can name the one id that
  // matters for the board it is claiming instead of one id for the whole build.
  const simLevels = require('./lib/sim-fingerprint.js').simLevels(path.join(__dirname, '..'));
  const idxPath = path.join(distDir, 'index.html');
  const before = fs.readFileSync(idxPath, 'utf8');
  const after = before.replace('window.__SIM_ID = null;',
    'window.__SIM_ID = ' + JSON.stringify(simId) + '; window.__SIM_LEVELS = ' + JSON.stringify(simLevels) + ';');
  if (after === before) {
    console.error('✗ could not stamp the sim id — the marker in src/index.html moved.');
    console.error('  The server can no longer tell an outdated client from a forged run. Fix before shipping.');
    process.exit(1);
  }
  fs.writeFileSync(idxPath, after);
  console.log('✓ sim id stamped: ' + simId + ' (+' + Object.keys(simLevels).length + ' board ids)');
}

console.log('✓ dist/ staged: ' + (bytes / 1048576).toFixed(1) + ' MB shippable'
  + ' (' + copied + ' file(s) copied, ' + skipped + ' excluded)');

// ---- verifier staleness guard ----
// The leaderboard verifier is a BUNDLE of the sim, deployed separately. If the
// sim or the campaign data moves and the bundle is not rebuilt and redeployed,
// the server replays every submission against the old rules and rejects them
// all — "verification failed [900 vs 26200]" — which looks like a scoring bug
// and is not one. Nothing in the game surfaces the mismatch, so the build does.
{
  const repo = path.join(__dirname, '..');
  const simPath = path.join(repo, 'supabase', 'functions', 'submit-run', '_sim.mjs');
  if (fs.existsSync(simPath)) {
    const built = fs.statSync(simPath).mtimeMs;
    const gameDir = path.join(repo, 'src', 'game');
    const watched = ['src/campaigns.js'].concat(
      fs.existsSync(gameDir)
        ? fs.readdirSync(gameDir).filter(f => f.endsWith('.js')).map(f => 'src/game/' + f)
        : []
    );
    const stale = watched
      .filter(f => fs.existsSync(path.join(repo, f)) && fs.statSync(path.join(repo, f)).mtimeMs > built);
    if (stale.length) {
      const named = stale.length > 3 ? stale.slice(0, 3).join(', ') + ' and ' + (stale.length - 3) + ' more' : stale.join(' and ');
      console.warn('\n! VERIFIER IS STALE — ' + named + ' changed after the bundle was built.');
      console.warn('  Leaderboard submissions will be REJECTED until you run:');
      console.warn('    npm run build:verifier && npm run deploy:verifier\n');
    }
  }
}
