// DATA DEFENDERS: DARK FIBER — bundled campaign packages.
// One self-contained, JSON-shaped object per campaign (no functions): the
// exact format the Tunnel Designer exports and future community packages
// will use. Loaded before the game script; every package still passes
// validateCampaign() on install. See docs/CMS-ROADMAP.md.
const CAMPAIGN_PACKAGES = [{
  id: 'investigation', format: 1,
  title: 'THE INVESTIGATION', tagline: 'OMNISERVE HQ · POLICE CID', difficulty: 1,
  story: 'OmniServe HQ must deliver critical evidence to the CID across one fiber line. You are the hired defender who clears it, relay by relay, while the investigation uncovers who is trying to burn the evidence.',
  map: { theme: 'city' }, // procedural city; image maps carry { image, pins }
  speakers: [
    { id: 'OMNI',  name: 'OmniServe HQ', color: '111,227,255', portrait: { drawn: 'OMNI' } },
    { id: 'CID',   name: 'Cyber Investigations Dept', color: '235,245,255', portrait: { drawn: 'CID' } },
    { id: 'TRACE', name: 'CID tracer analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'CORE',  name: 'CID Gateway core', color: '212,101,255', portrait: { drawn: 'CORE' } }
  ],
  levels: [
    { name: 'OMNISERVE CAMPUS', tint: '80,160,255', duration: 40, spawnMin: 1.50, spawnMax: 2.30, speed: 0.34, doubles: 0.00, heavies: 0.00, lines: 0.00, colors: 0.00, track: 0,
      story: { title: 'LOG 01 — THE CONTRACT', lines: [
        'OmniServe HQ must deliver evidence', 'to the CID across one fiber line.',
        'You were hired to keep it clean.', 'Taps are already on the wire.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'payload staged. handshake nominal.' },
              { t: 16, s: 'CID', m: 'copy. evidence intake is open.' },
              { t: 28, s: 'OMNI', m: 'then who else is on this line?' }],
      caseNote: 'CASE NOTE: tap signatures logged. someone is listening.' },
    { name: 'OLD TOWN GRID', tint: '255,170,90', duration: 50, spawnMin: 1.05, spawnMax: 1.80, speed: 0.40, doubles: 0.30, heavies: 0.22, lines: 0.00, colors: 0.00, track: 1,
      hint: 'NEW THREAT: heavy armor — dock both nodes and HOLD',
      story: { title: 'LOG 02 — PATTERN', lines: [
        'These taps are not random noise.', 'Same make. Same timing.',
        'Someone wants the evidence gone.', 'The CID opens a case file.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'tap signatures match. one operator.' },
              { t: 20, s: 'CID', m: 'we are being read. keep transmitting.' },
              { t: 36, s: 'OMNI', m: 'the case files? someone knows.' }],
      caseNote: 'CASE NOTE: one operator confirmed. the CID opens a file.' },
    { name: 'METRO EXCHANGE', tint: '110,230,200', duration: 55, spawnMin: 0.95, spawnMax: 1.70, speed: 0.43, doubles: 0.30, heavies: 0.22, lines: 0.00, colors: 0.00, frags: 0.12, track: 2, bursts: true,
      hint: 'NEW THREAT: burst transmissions — traps arrive in volleys',
      story: { title: 'LOG 03 — TRAPS', lines: [
        'Volleys now — probing our reflexes.', 'And they seeded the line with',
        'NODE KILLERS: black traps that fry', 'any node that touches them.'] },
      comms: [{ t: 6, s: 'CID', m: 'black packets are node killers. do not touch.' },
              { t: 22, s: 'OMNI', m: 'who plants traps inside a live line?' },
              { t: 36, s: 'CID', m: 'someone who knows how we defend it.' }],
      caseNote: 'CASE NOTE: recovered node killers are factory-made.' },
    { name: 'HARBOR CROSSING', tint: '70,205,235', duration: 60, spawnMin: 0.85, spawnMax: 1.55, speed: 0.46, doubles: 0.35, heavies: 0.20, lines: 0.20, colors: 0.00, frags: 0.13, track: 0,
      hint: 'NEW THREAT: barrier lines — one node on each end',
      story: { title: 'LOG 04 — THE HARBOR', lines: [
        'Barrier taps under the harbor mud —', 'walls strung to catch the payload',
        'whole. Cutting a subsea line takes', 'resources. This is no lone hacker.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'barrier debris under the harbor mud.' },
              { t: 20, s: 'OMNI', m: 'a subsea cut needs a crew and money.' },
              { t: 36, s: 'CID', m: 'or a badge.' }],
      caseNote: 'CASE NOTE: a subsea cut takes resources. or a badge.' },
    { name: 'UNDERCITY FIBER', tint: '150,110,255', duration: 60, spawnMin: 0.72, spawnMax: 1.35, speed: 0.46, doubles: 0.40, heavies: 0.20, lines: 0.20, colors: 0.00, frags: 0.14, walls: 0.10, track: 1,
      hint: 'NEW THREAT: rim walls — the rail closes, route around',
      story: { title: 'LOG 05 — UNDERCITY', lines: [
        'They chain their traps now — walls', 'of them, sealing whole sections of',
        'the rail. We traced the deployment', 'key: it holds CID clearance.'] },
      comms: [{ t: 6, s: 'CID', m: 'they are walling the rail. reroute.' },
              { t: 20, s: 'TRACE', m: 'deployment key holds active clearance.' },
              { t: 34, s: 'CID', m: 'log it. tell no one.' }],
      caseNote: 'CASE NOTE: the wall deployment key holds active clearance.' },
    { name: 'FINANCIAL SPINE', tint: '255,205,80', duration: 65, spawnMin: 0.68, spawnMax: 1.25, speed: 0.48, doubles: 0.42, heavies: 0.18, lines: 0.18, colors: 0.40, frags: 0.16, walls: 0.10, track: 2,
      hint: 'NEW THREAT: color-locked traps — match the node color',
      story: { title: 'LOG 06 — CREDENTIALS', lines: [
        'Keyed taps — cut with CURRENT keys,', 'rotated this very morning. Whoever',
        'hunts this line holds live clearance.', 'OMNI or CID. Trust no one.'] },
      comms: [{ t: 6, s: 'CID', m: 'rotate all credentials. now.' },
              { t: 20, s: 'TRACE', m: 'locks cut with keys rotated TODAY.' },
              { t: 36, s: 'OMNI', m: 'inside. it is someone inside.' }],
      caseNote: 'CASE NOTE: keys rotated TODAY. the leak is inside.' },
    { name: 'DARKNET EDGE', tint: '255,70,100', duration: 70, spawnMin: 0.58, spawnMax: 1.10, speed: 0.54, doubles: 0.48, heavies: 0.22, lines: 0.22, colors: 0.36, frags: 0.20, walls: 0.15, track: 0, bursts: true,
      hint: 'ALL THREATS ACTIVE — maximum traffic',
      story: { title: 'LOG 07 — SIGNATURE', lines: [
        'Every tap signature matches one', 'system: the CID GATEWAY itself.',
        'The firewall meant to receive the', 'evidence is burning it instead.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'signature isolated: CID GATEWAY core.' },
              { t: 20, s: 'OMNI', m: 'the receiver is the thief.' },
              { t: 36, s: 'CID', m: '…purge authorized. deliver it.' }],
      caseNote: 'CASE NOTE: signature match — CID GATEWAY. purge authorized.' },
    { name: 'CID GATEWAY', tint: '212,101,255', duration: 45, spawnMin: 0.80, spawnMax: 1.40, speed: 0.50, doubles: 0.35, heavies: 0.20, lines: 0.20, colors: 0.30, frags: 0.15, walls: 0.10, track: 2, boss: true,
      hint: 'THE FIREWALL CORE AWAITS — six bolts close the case',
      story: { title: 'LOG 08 — THE GATEWAY', lines: [
        'The gateway core was turned — bought', 'to keep the evidence out of court.',
        'Purge it, deliver the payload,', 'and close the case.'] },
      comms: [{ t: 4, s: 'CORE', m: 'the evidence is contaminated. I am the cure.' },
              { t: 16, s: 'CID', m: 'burn it out, defender. close the case.' }],
      caseNote: 'CASE CLOSED: gateway purged. evidence delivered.' }
  ],
  verdict: { title: 'LOG 09 — VERDICT', lines: [
    'The gateway burned. The payload', 'reached the CID intact. Warrants',
    'went out within the hour — the', 'buyer wore a badge. Case closed.'] }
},
{
  id: 'going-deeper', format: 1,
  title: 'GOING DEEPER', tagline: 'THE CORRUPTION CASE', difficulty: 2,
  story: 'The gateway burned and a buyer wore a badge — but a badge takes orders. Someone above the arrest is still burning evidence, and every wire you defend digs one layer closer to whoever is behind the corruption.',
  map: { theme: 'city' },
  speakers: [
    { id: 'OMNI',  name: 'OmniServe HQ', color: '111,227,255', portrait: { drawn: 'OMNI' } },
    { id: 'CID',   name: 'Cyber Investigations Dept', color: '235,245,255', portrait: { drawn: 'CID' } },
    { id: 'TRACE', name: 'CID tracer analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'CORE',  name: 'an unregistered core', color: '212,101,255', portrait: { drawn: 'CORE' } }
  ],
  levels: [
    { name: 'EVIDENCE VAULT', tint: '96,180,255', duration: 50, spawnMin: 0.75, spawnMax: 1.30, speed: 0.46, doubles: 0.45, heavies: 0.08, lines: 0.00, colors: 0.00, frags: 0.08, track: 1,
      hint: 'volume over trickery — ride the stream, keep the combo',
      bands: [{ t0: 28, t1: 44, intensity: 1.5 }],
      story: { title: 'LOG 10 — REOPENED', lines: [
        'The buyer wore a badge. He also', 'took orders. Tonight the sealed',
        'case archive is being scrubbed —', 'someone above him is still awake.'] },
      comms: [{ t: 6, s: 'CID', m: 'the vault line is live. hold it.' },
              { t: 20, s: 'TRACE', m: 'these taps know our sealed filenames.' },
              { t: 36, s: 'OMNI', m: 'sealed means six people. count them.' }],
      caseNote: 'CASE NOTE: the scrub list matches SEALED files. six suspects.' },
    { name: 'PRECINCT LOOP', tint: '255,160,80', duration: 55, spawnMin: 0.68, spawnMax: 1.20, speed: 0.49, doubles: 0.50, heavies: 0.10, lines: 0.00, colors: 0.00, frags: 0.10, track: 2, bursts: true,
      hint: 'the loop runs HOT — pure traffic, find your rhythm',
      bands: [{ t0: 16, t1: 32, intensity: 1.5 }, { t0: 44, t1: 53, intensity: 1.8 }],
      story: { title: 'LOG 11 — THE LOOP', lines: [
        'We tapped the precinct intranet.', 'Whoever burns evidence files their',
        'overtime on this loop. Defend the', 'wire while TRACE reads the badges.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'pulling duty rosters off the loop.' },
              { t: 22, s: 'CID', m: 'four of the six were on shift. narrow it.' },
              { t: 38, s: 'OMNI', m: 'and two of them signed the gateway PO.' }],
      caseNote: 'CASE NOTE: two signatures on the gateway purchase order.' },
    { name: 'INTERNAL AFFAIRS', tint: '120,230,190', duration: 60, spawnMin: 0.62, spawnMax: 1.10, speed: 0.52, doubles: 0.50, heavies: 0.10, lines: 0.00, colors: 0.15, frags: 0.12, track: 0,
      hint: 'keyed taps in the flood — glance, match, keep moving',
      bands: [{ t0: 30, t1: 48, intensity: 1.6 }],
      story: { title: 'LOG 12 — CLEAN HANDS', lines: [
        'Internal Affairs opened their own', 'file — then their line lit up with',
        'keyed taps cut from IA credentials.', 'The watchers are being watched.'] },
      comms: [{ t: 6, s: 'CID', m: 'IA is compromised. assume everything leaks.' },
              { t: 22, s: 'TRACE', m: 'keys cut from an IA terminal. inside again.' },
              { t: 38, s: 'CID', m: 'clean hands. dirty terminal. noted.' }],
      caseNote: 'CASE NOTE: the IA leak runs through ONE terminal. logged.' },
    { name: 'SHELL EXCHANGE', tint: '255,205,90', duration: 60, spawnMin: 0.58, spawnMax: 1.00, speed: 0.55, doubles: 0.55, heavies: 0.12, lines: 0.00, colors: 0.15, frags: 0.12, track: 1, bursts: true,
      hint: 'burst volleys — the flood comes in waves now',
      bands: [{ t0: 24, t1: 42, intensity: 1.7, mix: { doubles: 0.6 } }],
      story: { title: 'LOG 13 — PAPER WALLS', lines: [
        'The gateway money moved through', 'shell companies — eleven names,',
        'one drawer. They flood the line', 'with noise to bury one transfer.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'eleven shells, one registered drawer.' },
              { t: 24, s: 'TRACE', m: 'volley pattern says: hiding ONE packet.' },
              { t: 40, s: 'CID', m: 'find the packet they protect. follow it.' }],
      caseNote: 'CASE NOTE: one transfer matters. the rest is smoke.' },
    { name: 'LAUNDRY LINE', tint: '150,120,255', duration: 65, spawnMin: 0.55, spawnMax: 0.95, speed: 0.57, doubles: 0.55, heavies: 0.10, lines: 0.08, colors: 0.18, frags: 0.14, walls: 0.06, track: 2,
      hint: 'walls in the current — reroute without losing the beat',
      bands: [{ t0: 28, t1: 46, intensity: 1.6 }],
      story: { title: 'LOG 14 — THE WASH', lines: [
        'The transfer washes through a', 'crypto mixer under the old mint.',
        'They wall the rail while value', 'moves. Route around. Stay on it.'] },
      comms: [{ t: 6, s: 'CID', m: 'they wall the rail on every wash cycle.' },
              { t: 24, s: 'TRACE', m: 'mixer output pings a BLACKSITE relay.' },
              { t: 40, s: 'OMNI', m: 'a blacksite. of course it is.' }],
      caseNote: 'CASE NOTE: the wash empties into a blacksite relay.' },
    { name: 'BLACKSITE RELAY', tint: '255,90,110', duration: 70, spawnMin: 0.50, spawnMax: 0.90, speed: 0.60, doubles: 0.60, heavies: 0.14, lines: 0.08, colors: 0.18, frags: 0.16, walls: 0.08, track: 0, bursts: true,
      hint: 'blacksite pace — the fastest line yet',
      bands: [{ t0: 26, t1: 44, intensity: 1.8 }, { t0: 56, t1: 66, intensity: 2.0 }],
      story: { title: 'LOG 15 — OFF THE BOOKS', lines: [
        'The relay is not on any network', 'map. Government-grade hardware,',
        'zero paperwork. Nobody builds a', 'blacksite for one dirty badge.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'this hardware matches the gateway spec.' },
              { t: 26, s: 'CID', m: 'same vendor. same signature. same hand.' },
              { t: 44, s: 'OMNI', m: 'the paymaster built BOTH. find him.' }],
      caseNote: 'CASE NOTE: gateway and blacksite share one paymaster.' },
    { name: 'THE PAYMASTER', tint: '255,70,160', duration: 75, spawnMin: 0.48, spawnMax: 0.85, speed: 0.63, doubles: 0.60, heavies: 0.15, lines: 0.10, colors: 0.20, frags: 0.18, walls: 0.08, track: 1, bursts: true,
      hint: 'his ledger floods the line — survive the torrent',
      bands: [{ t0: 18, t1: 38, intensity: 1.7 }, { t0: 52, t1: 70, intensity: 2.1, mix: { doubles: 0.65 } }],
      story: { title: 'LOG 16 — THE LEDGER', lines: [
        'A name signs every invoice: a', 'commissioner-level login, retired',
        'on paper for six years. His ledger', 'syncs tonight. Take the line.'] },
      comms: [{ t: 6, s: 'CID', m: 'a retired login signing live invoices.' },
              { t: 28, s: 'TRACE', m: 'ledger sync begins. defend the intercept.' },
              { t: 48, s: 'OMNI', m: 'he knows we are reading. he is proud.' }],
      caseNote: 'CASE NOTE: the ledger names every buyer. one login signs.' },
    { name: 'BADGE ZERO', tint: '212,101,255', duration: 50, spawnMin: 0.70, spawnMax: 1.25, speed: 0.55, doubles: 0.45, heavies: 0.16, lines: 0.10, colors: 0.22, frags: 0.14, walls: 0.08, track: 2, boss: true, bossKind: 'triad',
      hint: 'his private core is THREE — shield, shredder, alibi. break each',
      story: { title: 'LOG 17 — BADGE ZERO', lines: [
        'He built himself a private core', 'from the stolen gateway schematics',
        '— his shield, his shredder, his', 'alibi. Burn it. End the ladder.'] },
      comms: [{ t: 4, s: 'CORE', m: 'my maker is untouchable. so am I.' },
              { t: 16, s: 'CID', m: 'three heads, one snake. take them all.' }],
      caseNote: 'CASE CLOSED: badge zero indicted. the ladder is ash.' }
  ],
  verdict: { title: 'LOG 18 — THE LADDER', lines: [
    'The private core burned with the', 'ledger open. Every name on it was',
    'served by morning — badge zero', 'first. The line is finally quiet.'] }
},
{
  id: 'signal-lost', format: 1,
  title: 'SIGNAL LOST', tagline: 'THE DEAD COAST', difficulty: 3,
  story: 'Badge Zero is served — and a whole coastal relay chain goes dark overnight. No breach, no ransom, just silence. Its automated defenses still run with no master, and something has re-lit the dead beacon at the end of the line.',
  map: { theme: 'city' },
  speakers: [
    { id: 'OMNI',  name: 'OmniServe HQ', color: '111,227,255', portrait: { drawn: 'OMNI' } },
    { id: 'CID',   name: 'Cyber Investigations Dept', color: '235,245,255', portrait: { drawn: 'CID' } },
    { id: 'TRACE', name: 'CID tracer analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'CORE',  name: 'the beacon', color: '255,230,120', portrait: { drawn: 'CORE' } }
  ],
  levels: [
    { name: 'DEAD HARBOR', tint: '80,200,215', duration: 55, spawnMin: 1.00, spawnMax: 1.65, speed: 0.48, doubles: 0.30, heavies: 0.18, lines: 0.30, colors: 0.35, frags: 0.10, track: 0,
      hint: 'a dead grid — every tap here was left ON PURPOSE',
      story: { title: 'LOG 19 — SIGNAL LOST', lines: [
        'Badge Zero is served. Then a whole', 'coastal relay chain drops off the',
        'map overnight. No breach, no ransom', '— just silence. We go in dark.'] },
      comms: [{ t: 6, s: 'CID', m: 'the coast line is dark. all of it.' },
              { t: 22, s: 'TRACE', m: 'defenses live, operators gone. eerie.' },
              { t: 40, s: 'OMNI', m: 'who taps a line nobody runs?' }],
      caseNote: 'CASE NOTE: the coast went dark on a SCHEDULE. planned silence.' },
    { name: 'GHOST CURRENT', tint: '110,225,170', duration: 55, spawnMin: 0.60, spawnMax: 1.00, speed: 0.58, doubles: 0.60, heavies: 0.06, lines: 0.00, colors: 0.00, frags: 0.10, track: 1, bursts: true,
      hint: 'the current still runs — fast, blind, and full',
      bands: [{ t0: 15, t1: 30, intensity: 1.7 }, { t0: 40, t1: 52, intensity: 1.9 }],
      story: { title: 'LOG 20 — GHOST CURRENT', lines: [
        'The line still carries traffic.', 'Nobody sends it. Nobody reads it.',
        'Ghost packets on a dead current —', 'and something is EATING them.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'traffic with no sender. recorded loops.' },
              { t: 24, s: 'OMNI', m: 'a dead line that will not die.' },
              { t: 44, s: 'CID', m: 'ride it. see where it drains.' }],
      caseNote: 'CASE NOTE: the ghost traffic drains toward the old lighthouse hub.' },
    { name: 'CIPHER SHOALS', tint: '255,190,110', duration: 60, spawnMin: 0.95, spawnMax: 1.50, speed: 0.50, doubles: 0.35, heavies: 0.20, lines: 0.28, colors: 0.45, frags: 0.14, walls: 0.12, track: 2,
      hint: 'shoal water — keyed reefs and sealed pairs, read before you steer',
      beats: [{ t: 26, kind: 'wall' }, { t: 35, kind: 'strip' }, { t: 46, kind: 'wall' }],
      story: { title: 'LOG 21 — THE SHOALS', lines: [
        'The shallows are mined with keyed', 'taps cut years ago — still armed,',
        'still rotating their colors on a', 'dead man\u2019s schedule. Navigate.'] },
      comms: [{ t: 6, s: 'CID', m: 'old keys, still turning. mind the colors.' },
              { t: 20, s: 'TRACE', m: 'these locks predate badge zero. YEARS old.' },
              { t: 38, s: 'OMNI', m: 'then who has been winding them?' }],
      caseNote: 'CASE NOTE: the shoal locks are OLDER than the corruption case.' },
    { name: 'RIPTIDE', tint: '120,160,255', duration: 60, spawnMin: 0.55, spawnMax: 0.92, speed: 0.60, doubles: 0.65, heavies: 0.05, lines: 0.00, colors: 0.00, frags: 0.12, track: 0, bursts: true,
      hint: 'riptide — do not fight the pace, become it',
      bands: [{ t0: 12, t1: 28, intensity: 1.8 }, { t0: 36, t1: 54, intensity: 2.0, mix: { doubles: 0.7 } }],
      story: { title: 'LOG 22 — RIPTIDE', lines: [
        'The drain quickens near the hub.', 'Whole reels of ghost traffic pulled',
        'under at once. Hold the line in the', 'riptide and do not let go.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'flow rate doubled. tripled. keep up.' },
              { t: 30, s: 'CID', m: 'steady hands. it wants you rushed.' }],
      caseNote: 'CASE NOTE: the drain pulls harder the closer we get.' },
    { name: 'THE SHALLOWS', tint: '150,230,120', duration: 65, spawnMin: 0.90, spawnMax: 1.42, speed: 0.52, doubles: 0.35, heavies: 0.22, lines: 0.30, colors: 0.40, frags: 0.16, walls: 0.18, track: 1,
      hint: 'the rail closes in shallow water — plan two moves ahead',
      beats: [{ t: 24, kind: 'wall' }, { t: 40, kind: 'lull', dur: 5 }, { t: 52, kind: 'wall' }],
      story: { title: 'LOG 23 — THE SHALLOWS', lines: [
        'Wrecks everywhere: relays fried by', 'their own walls years ago. Whoever',
        'holds the beacon rehearsed this', 'exact defense — on these bones.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'wall scars on every wreck here.' },
              { t: 20, s: 'CID', m: 'this is a training ground. WAS.' },
              { t: 46, s: 'OMNI', m: 'so the beacon had a teacher once.' }],
      caseNote: 'CASE NOTE: the wrecks are practice targets. YEARS of drills.' },
    { name: 'UNDERTOW', tint: '255,120,140', duration: 70, spawnMin: 0.50, spawnMax: 0.86, speed: 0.63, doubles: 0.65, heavies: 0.12, lines: 0.00, colors: 0.00, frags: 0.18, track: 2, bursts: true,
      hint: 'undertow — the fastest water on the dead coast',
      bands: [{ t0: 14, t1: 34, intensity: 1.8 }, { t0: 46, t1: 64, intensity: 2.2 }],
      story: { title: 'LOG 24 — UNDERTOW', lines: [
        'Under the surface current there is', 'a second one, running the OTHER',
        'way — carrying copies of everything', 'we transmit straight to the hub.'] },
      comms: [{ t: 6, s: 'CID', m: 'it reads us as we ride. shield nothing.' },
              { t: 38, s: 'TRACE', m: 'copies of OUR traffic in the drain.' }],
      caseNote: 'CASE NOTE: the beacon has been listening since relay one.' },
    { name: 'THE NARROWS', tint: '210,140,255', duration: 75, spawnMin: 0.58, spawnMax: 0.98, speed: 0.58, doubles: 0.50, heavies: 0.22, lines: 0.26, colors: 0.40, frags: 0.20, walls: 0.18, track: 0, bursts: true,
      hint: 'the narrows: every trick on the coast, then open water',
      beats: [{ t: 31, kind: 'wall' }, { t: 50, kind: 'wall' }, { t: 62, kind: 'strip' }],
      bands: [{ t0: 34, t1: 48, intensity: 1.9 }],
      story: { title: 'LOG 25 — THE NARROWS', lines: [
        'One channel left. It is everything', 'at once: keys, walls, pairs, ghost',
        'floods. The beacon watches us', 'thread it. It is almost polite.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'it is WAITING for us now.' },
              { t: 26, s: 'TRACE', m: 'signal ahead. clean. an invitation.' },
              { t: 54, s: 'CID', m: 'accept it. weapons hot.' }],
      caseNote: 'CASE NOTE: it let us through. it wanted an audience.' },
    { name: 'THE BEACON', tint: '255,230,120', duration: 50, spawnMin: 0.80, spawnMax: 1.40, speed: 0.55, doubles: 0.35, heavies: 0.18, lines: 0.20, colors: 0.30, frags: 0.14, walls: 0.10, track: 1, boss: true, bossKind: 'spinner',
      hint: 'ride the light — survive every sweep and the beacon burns itself out',
      story: { title: 'LOG 26 — THE LIGHT', lines: [
        'The beacon was built to guide. Left', 'alone with dead orders it guides',
        'still — burning every ship it sees.', 'Stay out of the light. Let it turn.'] },
      comms: [{ t: 4, s: 'CORE', m: 'i kept the light on. where were you?' },
              { t: 16, s: 'CID', m: 'ride the beam, defender. let it spend itself.' }],
      caseNote: 'CASE CLOSED: the light is out. the coast sleeps quiet.' }
  ],
  verdict: { title: 'LOG 27 — LIGHTS OUT', lines: [
    'The beacon burned through its own', 'charge and went dark for good. The',
    'coast came back online by morning.', 'Somewhere, a new case is waiting.'] }
},
{
  id: 'the-bait', format: 1,
  title: 'THE BAIT', tagline: 'FLUSH THE ARCHITECT', difficulty: 4,
  story: 'Every dead line traced back to one hand that never shows itself — the architect who built the gateway, the blacksite, and the beacon, and never once touched a wire. You cannot trace a man who never transmits. So we stop chasing and start fishing: the data you defend now is BAIT, dressed as the evidence he burns for, tuned to the colors his hunters cannot resist.',
  map: { theme: 'city' },
  speakers: [
    { id: 'OMNI',  name: 'OmniServe HQ', color: '111,227,255', portrait: { drawn: 'OMNI' } },
    { id: 'CID',   name: 'Cyber Investigations Dept', color: '235,245,255', portrait: { drawn: 'CID' } },
    { id: 'TRACE', name: 'CID tracer analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'CORE',  name: 'the Architect’s hunter', color: '212,120,255', portrait: { drawn: 'CORE' } }
  ],
  levels: [
    { name: 'DECOY RELAY', tint: '255,190,90', duration: 45, spawnMin: 0.90, spawnMax: 1.45, speed: 0.52, doubles: 0.35, heavies: 0.12, lines: 0.10, colors: 0.35, frags: 0.10, track: 0,
      hint: 'the data is BAIT now — dress it in his colors, make him bite',
      story: { title: 'LOG 28 — FLUSH HIM OUT', lines: [
        'One hand built them all and never', 'showed it — no line, no signature.',
        'You cannot trace a man who never', 'sends. So we make him reach for bait.'] },
      comms: [{ t: 6, s: 'CID', m: 'stop chasing. we fish now. bait is live.' },
              { t: 20, s: 'TRACE', m: 'decoy dressed as the sealed evidence.' },
              { t: 34, s: 'OMNI', m: 'if he wants it, he comes to us.' }],
      caseNote: 'CASE NOTE: the bait is on the wire. now we wait for a bite.' },
    { name: 'HONEYLINE', tint: '126,200,110', duration: 50, spawnMin: 0.80, spawnMax: 1.32, speed: 0.55, doubles: 0.40, heavies: 0.14, lines: 0.12, colors: 0.45, frags: 0.12, track: 1,
      hint: 'match the bait to the mark — wrong color, no bite',
      bands: [{ t0: 26, t1: 44, intensity: 1.5 }],
      story: { title: 'LOG 29 — HONEYLINE', lines: [
        'The first probes arrive — careful,', 'gloved, testing the bait for a hook.',
        'Each hunter answers one color only.', 'Tune the lure. Let them taste it.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'probes sniffing the decoy. keyed, picky.' },
              { t: 24, s: 'OMNI', m: 'they bite their own color. feed them.' },
              { t: 40, s: 'CID', m: 'good. he thinks the evidence is real.' }],
      caseNote: 'CASE NOTE: the hunters are color-keyed. each bites one lure.' },
    { name: 'MIRROR VAULT', tint: '90,200,235', duration: 55, spawnMin: 0.70, spawnMax: 1.18, speed: 0.58, doubles: 0.45, heavies: 0.14, lines: 0.14, colors: 0.50, frags: 0.12, walls: 0.06, track: 2, bursts: true,
      hint: 'the bite comes in volleys now — hold your colors steady',
      bands: [{ t0: 18, t1: 36, intensity: 1.6 }],
      beats: [{ t: 30, kind: 'strip' }],
      story: { title: 'LOG 30 — MIRROR VAULT', lines: [
        'We built a fake vault of fake files', 'and let him crack it. He took the',
        'frame whole — and left prints all', 'over the mirror. Ride the bite.'] },
      comms: [{ t: 6, s: 'CID', m: 'he breached the mirror. it is all decoy.' },
              { t: 24, s: 'TRACE', m: 'volleys now — he committed real hunters.' },
              { t: 42, s: 'OMNI', m: 'and real hunters have an address.' }],
      caseNote: 'CASE NOTE: his hunters carry a return path. TRACE has it.' },
    { name: 'CHUM RUN', tint: '255,150,70', duration: 60, spawnMin: 0.62, spawnMax: 1.05, speed: 0.60, doubles: 0.50, heavies: 0.16, lines: 0.16, colors: 0.45, frags: 0.14, walls: 0.08, track: 0, bursts: true,
      hint: 'blood in the water — the whole pack answers at once',
      bands: [{ t0: 22, t1: 40, intensity: 1.7, mix: { colors: 0.6 } }],
      story: { title: 'LOG 31 — CHUM RUN', lines: [
        'We spill the whole decoy cache — a', 'feast of counterfeit keys. The pack',
        'comes off the leash to feed, blind', 'and greedy. Do not choke on it.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'chum is out. every hunter he owns turned.' },
              { t: 26, s: 'TRACE', m: 'mapping each one back as it bites.' },
              { t: 44, s: 'CID', m: 'he taught them to feed, not think.' }],
      caseNote: 'CASE NOTE: the pack maps to ONE upstream core. we have him.' },
    { name: 'TRACEBACK', tint: '120,160,255', duration: 60, spawnMin: 0.56, spawnMax: 0.96, speed: 0.63, doubles: 0.50, heavies: 0.18, lines: 0.18, colors: 0.50, frags: 0.16, walls: 0.10, track: 1,
      hint: 'follow the bite home — keyed traffic all the way down',
      bands: [{ t0: 28, t1: 48, intensity: 1.7 }],
      story: { title: 'LOG 32 — TRACEBACK', lines: [
        'Every hunter reels back to the same', 'dark relay. We ride their tails home',
        'through his own keyed defenses —', 'wearing the colors he issued them.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'riding the pack home. his keys, his doors.' },
              { t: 26, s: 'CID', m: 'he lets his own hunters in. so do we.' },
              { t: 46, s: 'OMNI', m: 'closer. i can feel him watching.' }],
      caseNote: 'CASE NOTE: the traceback holds. the architect has a door.' },
    { name: 'THE APIARY', tint: '255,205,90', duration: 65, spawnMin: 0.52, spawnMax: 0.90, speed: 0.65, doubles: 0.55, heavies: 0.18, lines: 0.20, colors: 0.55, frags: 0.18, walls: 0.12, track: 2, bursts: true,
      hint: 'the nest — every color at once, and it is awake',
      bands: [{ t0: 20, t1: 38, intensity: 1.8 }, { t0: 50, t1: 63, intensity: 2.0, mix: { colors: 0.65 } }],
      story: { title: 'LOG 33 — THE APIARY', lines: [
        'His hunters nest in one hive of', 'fiber, thousands deep, every color',
        'keyed and humming. We walked in on', 'the bait. Now the hive knows our face.'] },
      comms: [{ t: 6, s: 'CID', m: 'the nest. every hunter he ever built.' },
              { t: 26, s: 'TRACE', m: 'they know the bait was a hook. hot now.' },
              { t: 48, s: 'OMNI', m: 'hold. he always answers his hive.' }],
      caseNote: 'CASE NOTE: the hive is his. he will surface to defend it.' },
    { name: 'OPEN LINE', tint: '255,90,110', duration: 70, spawnMin: 0.48, spawnMax: 0.82, speed: 0.68, doubles: 0.58, heavies: 0.22, lines: 0.22, colors: 0.50, frags: 0.20, walls: 0.15, track: 0, bursts: true,
      hint: 'he has committed everything — this is the whole swarm',
      bands: [{ t0: 16, t1: 36, intensity: 1.9 }, { t0: 50, t1: 68, intensity: 2.1, mix: { colors: 0.6, doubles: 0.65 } }],
      story: { title: 'LOG 34 — OPEN LINE', lines: [
        'To save the hive he does the one', 'thing he never does — he opens a',
        'line himself. Real traffic. A real', 'signature. We have him in the open.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'a live signature. HIS. first one ever.' },
              { t: 28, s: 'OMNI', m: 'the bait worked. he blinked. hold on.' },
              { t: 50, s: 'CID', m: 'lock the trace. we finish this next.' }],
      caseNote: 'CASE NOTE: the architect transmitted. we have his core.' },
    { name: 'THE HUNTER', tint: '212,120,255', duration: 50, spawnMin: 0.72, spawnMax: 1.28, speed: 0.60, doubles: 0.45, heavies: 0.20, lines: 0.18, colors: 0.40, frags: 0.16, walls: 0.10, track: 1, boss: true, bossKind: 'triad',
      hint: 'his hunter-core is THREE — the nose, the jaws, the ghost',
      story: { title: 'LOG 35 — THE HUNTER', lines: [
        'He sends his masterpiece to clean up', '— a hunter-core in three parts: the',
        'nose that found the bait, the jaws', 'that close, the ghost that escapes.'] },
      comms: [{ t: 4, s: 'CORE', m: 'clever bait. i taught them to bite. not me.' },
              { t: 16, s: 'CID', m: 'three heads. nose, jaws, and tail. all of it.' }],
      caseNote: 'CASE CLOSED: the hunter is scrap. the architect is exposed.' }
  ],
  verdict: { title: 'LOG 36 — THE ADDRESS', lines: [
    'The hunter died in three pieces and', 'the architect went silent — but too',
    'late. One live signature was all we', 'needed. We know where his core lives.'] }
},
{
  id: 'shutdown', format: 1,
  title: 'SHUTDOWN', tagline: 'UNWRITE THE ARCHITECT', difficulty: 5,
  story: 'The architect has a core, and now we have its address. There is no arrest for a man who never existed on paper — only a shutdown. OMNI hands you the last data you will ever escort: a virus, coded to unwrite his entire operation. Carry it down his line to his core. He knows it is coming, and everything he has left stands between it and the door.',
  map: { theme: 'city' },
  speakers: [
    { id: 'OMNI',  name: 'OmniServe HQ', color: '111,227,255', portrait: { drawn: 'OMNI' } },
    { id: 'CID',   name: 'Cyber Investigations Dept', color: '235,245,255', portrait: { drawn: 'CID' } },
    { id: 'TRACE', name: 'CID tracer analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'CORE',  name: 'the Architect', color: '212,101,255', portrait: { drawn: 'CORE' } }
  ],
  levels: [
    { name: 'INJECTION POINT', tint: '96,180,255', duration: 50, spawnMin: 0.72, spawnMax: 1.20, speed: 0.58, doubles: 0.50, heavies: 0.15, lines: 0.20, colors: 0.30, frags: 0.15, walls: 0.10, track: 0,
      hint: 'you carry a virus now — get it on his wire and hold on',
      story: { title: 'LOG 37 — SHUTDOWN', lines: [
        'No warrant reaches a man who never', 'existed. Only this: one virus, coded',
        'to unwrite him. You escort it to his', 'core. Everything he has will say no.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'payload is live and it is lethal. mind it.' },
              { t: 20, s: 'CID', m: 'this ends it. get it to his door intact.' },
              { t: 34, s: 'CORE', m: 'i see what you are carrying. turn back.' }],
      caseNote: 'CASE NOTE: the virus is on his line. he already knows.' },
    { name: 'THE GAUNTLET', tint: '255,160,80', duration: 55, spawnMin: 0.60, spawnMax: 1.02, speed: 0.63, doubles: 0.55, heavies: 0.16, lines: 0.22, colors: 0.32, frags: 0.16, walls: 0.12, track: 1, bursts: true,
      hint: 'his outer wall throws everything — do not slow the payload',
      bands: [{ t0: 18, t1: 36, intensity: 1.7 }],
      story: { title: 'LOG 38 — THE GAUNTLET', lines: [
        'His outer defenses wake all at once,', 'no longer hunting evidence — hunting',
        'the thing in your hands. They do not', 'probe now. They swing to kill.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'defenses full-live. he stopped pretending.' },
              { t: 24, s: 'OMNI', m: 'they want the payload, not you. shield it.' },
              { t: 44, s: 'CORE', m: 'you carry your own death in there.' }],
      caseNote: 'CASE NOTE: his line is all-in on stopping ONE packet. ours.' },
    { name: 'FIREWALL DELTA', tint: '120,230,190', duration: 60, spawnMin: 0.54, spawnMax: 0.92, speed: 0.66, doubles: 0.55, heavies: 0.18, lines: 0.26, colors: 0.35, frags: 0.18, walls: 0.18, track: 2,
      hint: 'walls stacked on walls — thread the virus through, do not clip it',
      beats: [{ t: 20, kind: 'wall' }, { t: 40, kind: 'wall' }, { t: 50, kind: 'strip' }],
      bands: [{ t0: 28, t1: 48, intensity: 1.7 }],
      story: { title: 'LOG 39 — FIREWALL DELTA', lines: [
        'A delta of firewalls fans across the', 'fiber, folding shut in sequence. He',
        'is trying to seal the virus in a dead', 'segment and starve it. Keep it moving.'] },
      comms: [{ t: 6, s: 'CID', m: 'he is walling it into a pocket. break out.' },
              { t: 26, s: 'TRACE', m: 'do not let the payload stall in a dead cell.' },
              { t: 46, s: 'CORE', m: 'quarantine holding. you cannot reach me.' }],
      caseNote: 'CASE NOTE: he cannot kill the virus — only try to trap it.' },
    { name: 'THE SCREAMING LINE', tint: '255,205,90', duration: 60, spawnMin: 0.50, spawnMax: 0.86, speed: 0.69, doubles: 0.60, heavies: 0.20, lines: 0.24, colors: 0.38, frags: 0.20, walls: 0.16, track: 0, bursts: true,
      hint: 'pure panic traffic — become the pace or drown in it',
      bands: [{ t0: 14, t1: 32, intensity: 1.9 }, { t0: 42, t1: 58, intensity: 2.1, mix: { doubles: 0.7 } }],
      story: { title: 'LOG 40 — THE SCREAMING LINE', lines: [
        'The line screams — he floods it with', 'everything at once, decades of tricks',
        'fired blind. This is not defense.', 'This is furniture thrown at a door.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'flow is off the chart. he is panicking.' },
              { t: 30, s: 'CID', m: 'steady. a panicked wall has holes.' },
              { t: 52, s: 'CORE', m: 'stop. STOP. you do not know what i built.' }],
      caseNote: 'CASE NOTE: the architect is out of plans. only noise left.' },
    { name: 'QUARANTINE', tint: '150,120,255', duration: 65, spawnMin: 0.46, spawnMax: 0.80, speed: 0.72, doubles: 0.60, heavies: 0.20, lines: 0.28, colors: 0.40, frags: 0.22, walls: 0.20, track: 1, bursts: true,
      hint: 'he seals every gate — keyed, walled, doubled. read fast',
      bands: [{ t0: 20, t1: 40, intensity: 1.9 }, { t0: 50, t1: 63, intensity: 2.2, mix: { colors: 0.55 } }],
      beats: [{ t: 34, kind: 'wall' }, { t: 48, kind: 'wall' }],
      story: { title: 'LOG 41 — QUARANTINE', lines: [
        'He falls back to the core and seals', 'it — every color keyed, every gate',
        'walled, the whole approach doubled.', 'The last ring before the man himself.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'he is inside the last ring. sealing it.' },
              { t: 28, s: 'OMNI', m: 'every gate keyed AND walled. thread it.' },
              { t: 50, s: 'CORE', m: 'i can hold this door forever. try me.' }],
      caseNote: 'CASE NOTE: one ring left. then his core, and the payload.' },
    { name: 'DEEP FIBER', tint: '255,90,110', duration: 70, spawnMin: 0.44, spawnMax: 0.76, speed: 0.75, doubles: 0.62, heavies: 0.22, lines: 0.26, colors: 0.42, frags: 0.22, walls: 0.20, track: 2, bursts: true,
      hint: 'the fastest water on any line — do not fight it, ride it',
      bands: [{ t0: 16, t1: 36, intensity: 2.0 }, { t0: 48, t1: 68, intensity: 2.2, mix: { doubles: 0.7, colors: 0.55 } }],
      story: { title: 'LOG 42 — DEEP FIBER', lines: [
        'Down where his core sits the fiber', 'runs hot enough to blur. No walls',
        'here — just speed, the last thing he', 'has. Outrun it. Carry it deeper.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'pace maxed. the payload is still alive. go.' },
              { t: 36, s: 'CID', m: 'almost on the core. do not lose it now.' },
              { t: 58, s: 'CORE', m: 'you are in my house. it will not save you.' }],
      caseNote: 'CASE NOTE: the virus is intact and one ring from the core.' },
    { name: 'THE THRESHOLD', tint: '255,70,160', duration: 75, spawnMin: 0.42, spawnMax: 0.72, speed: 0.78, doubles: 0.65, heavies: 0.25, lines: 0.28, colors: 0.45, frags: 0.25, walls: 0.22, track: 0, bursts: true,
      hint: 'everything he has, all at once, at full speed — the last door',
      bands: [{ t0: 18, t1: 38, intensity: 2.0 }, { t0: 52, t1: 72, intensity: 2.3, mix: { colors: 0.6, doubles: 0.72 } }],
      beats: [{ t: 34, kind: 'wall' }, { t: 62, kind: 'wall' }],
      story: { title: 'LOG 43 — THE THRESHOLD', lines: [
        'The threshold of his core: every', 'weapon he ever made, firing at full',
        'speed into one narrow gate. He knows', 'if you cross it, he ends. Cross it.'] },
      comms: [{ t: 6, s: 'CID', m: 'last door. he threw it all on this one.' },
              { t: 30, s: 'TRACE', m: 'gap coming. the virus only needs one.' },
              { t: 56, s: 'CORE', m: 'i built all of it. you are NOTHING.' }],
      caseNote: 'CASE NOTE: threshold breached. the core is open. deliver it.' },
    { name: 'THE ARCHITECT', tint: '212,101,255', duration: 55, spawnMin: 0.68, spawnMax: 1.22, speed: 0.66, doubles: 0.50, heavies: 0.22, lines: 0.20, colors: 0.40, frags: 0.20, walls: 0.14, track: 1, boss: true, bossKind: 'core',
      hint: 'THE ARCHITECT — six injections seat the virus and shut him down',
      story: { title: 'LOG 44 — THE ARCHITECT', lines: [
        'The core that built the gateway, the', 'blacksite, the beacon, the hive — one',
        'quiet machine that never had a face.', 'Seat the virus. Give it one.'] },
      comms: [{ t: 4, s: 'CORE', m: 'i am every case you ever closed. you cannot—' },
              { t: 16, s: 'OMNI', m: 'inject it, defender. shut him down for good.' }],
      caseNote: 'CASE CLOSED: the architect is unwritten. every line goes quiet.' }
  ],
  verdict: { title: 'LOG 45 — CLEAN FIBER', lines: [
    'The virus seated and the architect', 'unwrote himself, line by line — every',
    'dead case he ever built going dark', 'behind him. The fiber is clean at last.'] }
}];
