// WARP OVERWATCH: LANE VANGUARDS — bundled campaign packages.
// One self-contained, JSON-shaped object per campaign (no functions): the
// exact format the Lane Designer exports and future community packages
// will use. Loaded before the game script; every package still passes
// validateCampaign() on install. See docs/CMS-ROADMAP.md.
const CAMPAIGN_PACKAGES = [{
  id: 'investigation', format: 1,
  title: 'LOW ORBIT', tagline: 'THE INVESTIGATION · MERIDIAN HAULAGE', difficulty: 1,
  story: 'Meridian Haulage must run one sealed manifest to Lane Command down a single warp lane. You fly point ahead of the convoy and clear it, relay by relay, while the investigation uncovers who keeps interdicting the evidence.',
  map: { theme: 'chart' }, // procedural lane chart; image maps carry { image, pins }
  speakers: [
    { id: 'HAUL',  name: 'Meridian Haulage', color: '111,227,255', portrait: { drawn: 'HAUL' } },
    { id: 'CMD',   name: 'Lane Command', color: '235,245,255', portrait: { drawn: 'CMD' } },
    { id: 'TRACE', name: 'Lane Command trace analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'WARD',  name: 'Command Gateway warden', color: '212,101,255', portrait: { drawn: 'WARD' } }
  ],
  levels: [
    { name: 'MERIDIAN HAULAGE', tint: '80,160,255', duration: 40, spawnMin: 1.50, spawnMax: 2.30, speed: 0.34, doubles: 0.00, heavies: 0.00, lines: 0.00, colors: 0.00, track: 0,
      story: { line: 'One lane. One convoy. Interdictors already seeded.' },
      comms: [{ t: 6, s: 'HAUL', m: 'convoy formed up. lane clearance nominal.' },
              { t: 16, s: 'CMD', m: 'copy. evidence intake is open.' },
              { t: 28, s: 'HAUL', m: 'then who else is in this lane?' }],
      caseNote: 'CASE NOTE: interdictor marks logged. someone is watching.' },
    { name: 'OLD MOORINGS', tint: '255,170,90', duration: 50, spawnMin: 1.05, spawnMax: 1.80, speed: 0.40, doubles: 0.30, heavies: 0.22, lines: 0.00, colors: 0.00, track: 1,
      hint: 'NEW THREAT: heavy armor — dock both emitters and HOLD',
      story: { line: 'Same foundry, same timing. One dispatcher.' },
      comms: [{ t: 6, s: 'TRACE', m: 'interdictor marks match. one dispatcher.' },
              { t: 20, s: 'CMD', m: 'we are being watched. keep hauling.' },
              { t: 36, s: 'HAUL', m: 'the manifests? someone knows.' }],
      caseNote: 'CASE NOTE: one dispatcher confirmed. Lane Command opens a file.' },
    { name: 'TRANSIT EXCHANGE', tint: '110,230,200', duration: 55, spawnMin: 0.95, spawnMax: 1.70, speed: 0.43, doubles: 0.30, heavies: 0.22, lines: 0.00, colors: 0.00, frags: 0.12, track: 2, bursts: true,
      hint: 'NEW THREAT: burst deployments — threats arrive in volleys',
      story: { line: 'Volleys now, and black charges that fry emitters.' },
      comms: [{ t: 6, s: 'CMD', m: 'black charges are emitter killers. do not touch.' },
              { t: 22, s: 'HAUL', m: 'who mines a lane with traffic still in it?' },
              { t: 36, s: 'CMD', m: 'someone who knows how we escort it.' }],
      caseNote: 'CASE NOTE: recovered emitter killers are factory-made.' },
    { name: 'HARBOR CROSSING', tint: '70,205,235', duration: 60, spawnMin: 0.85, spawnMax: 1.55, speed: 0.46, doubles: 0.35, heavies: 0.20, lines: 0.20, colors: 0.00, frags: 0.13, track: 0,
      hint: 'NEW THREAT: barrier lines — one emitter on each end',
      story: { line: 'Barrier nets strung clean across the crossing.' },
      comms: [{ t: 6, s: 'TRACE', m: 'barrier debris drifting the whole crossing.' },
              { t: 20, s: 'HAUL', m: 'a net that wide needs a crew and money.' },
              { t: 36, s: 'CMD', m: 'or a badge.' }],
      caseNote: 'CASE NOTE: a net that wide takes resources. or a badge.' },
    { name: 'SUBLANE DRIFT', tint: '150,110,255', duration: 60, spawnMin: 0.72, spawnMax: 1.35, speed: 0.46, doubles: 0.40, heavies: 0.20, lines: 0.20, colors: 0.00, frags: 0.14, walls: 0.10, track: 1,
      hint: 'NEW THREAT: rim walls — the rail closes, route around',
      story: { line: 'They wall whole sections of the rail now.' },
      comms: [{ t: 6, s: 'CMD', m: 'they are walling the rail. reroute.' },
              { t: 20, s: 'TRACE', m: 'deployment key holds active clearance.' },
              { t: 34, s: 'CMD', m: 'log it. tell no one.' }],
      caseNote: 'CASE NOTE: the wall deployment key holds active clearance.' },
    { name: 'TRADE SPINE', tint: '255,205,80', duration: 65, spawnMin: 0.68, spawnMax: 1.25, speed: 0.48, doubles: 0.42, heavies: 0.18, lines: 0.18, colors: 0.40, frags: 0.16, walls: 0.10, track: 2,
      hint: 'NEW THREAT: phase-locked threats — match the emitter',
      story: { line: 'The phase keys were cut this morning.' },
      comms: [{ t: 6, s: 'CMD', m: 'rotate every clearance. now.' },
              { t: 20, s: 'TRACE', m: 'locks cut with keys rotated TODAY.' },
              { t: 36, s: 'HAUL', m: 'inside. it is someone inside.' }],
      caseNote: 'CASE NOTE: keys rotated TODAY. the leak is inside.' },
    { name: 'THE DARK EDGE', tint: '255,70,100', duration: 70, spawnMin: 0.58, spawnMax: 1.10, speed: 0.54, doubles: 0.48, heavies: 0.22, lines: 0.22, colors: 0.36, frags: 0.20, walls: 0.15, track: 0, bursts: true,
      hint: 'ALL THREATS ACTIVE — maximum traffic',
      story: { line: 'Every signature points at the receiver.' },
      comms: [{ t: 6, s: 'TRACE', m: 'signature isolated: COMMAND GATEWAY warden.' },
              { t: 20, s: 'HAUL', m: 'the receiver is the thief.' },
              { t: 36, s: 'CMD', m: '…purge authorized. deliver it.' }],
      caseNote: 'CASE NOTE: signature match — COMMAND GATEWAY. purge authorized.' },
    { name: 'COMMAND GATEWAY', tint: '212,101,255', duration: 45, spawnMin: 0.80, spawnMax: 1.40, speed: 0.50, doubles: 0.35, heavies: 0.20, lines: 0.20, colors: 0.30, frags: 0.15, walls: 0.10, track: 2, boss: true,
      hint: 'THE WARDEN CORE AWAITS — six bolts close the case',
      story: { line: 'The gateway was bought. Purge it.' },
      comms: [{ t: 4, s: 'WARD', m: 'the manifest is contaminated. I am the cure.' },
              { t: 16, s: 'CMD', m: 'burn it out, runner. close the case.' }],
      caseNote: 'CASE CLOSED: gateway purged. cargo delivered.' }
  ],
  verdict: { title: 'LOG 09 — VERDICT', lines: [
    'The gateway burned. The convoy', 'reached Lane Command intact. Warrants',
    'went out within the hour — the', 'buyer wore a badge. Case closed.'] }
},
{
  id: 'going-deeper', format: 1,
  title: 'MONITORED SECTORS', tagline: 'GOING DEEPER · THE CORRUPTION CASE', difficulty: 2,
  story: 'The gateway burned and a buyer wore a badge — but a badge takes orders. Someone above the arrest is still burning manifests, and every lane you run digs one layer closer to whoever is behind the corruption.',
  map: { theme: 'chart' },
  speakers: [
    { id: 'HAUL',  name: 'Meridian Haulage', color: '111,227,255', portrait: { drawn: 'HAUL' } },
    { id: 'CMD',   name: 'Lane Command', color: '235,245,255', portrait: { drawn: 'CMD' } },
    { id: 'TRACE', name: 'Lane Command trace analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'WARD',  name: 'an unregistered warden', color: '212,101,255', portrait: { drawn: 'WARD' } }
  ],
  levels: [
    { name: 'EVIDENCE VAULT', tint: '96,180,255', duration: 50, spawnMin: 0.75, spawnMax: 1.30, speed: 0.46, doubles: 0.45, heavies: 0.08, lines: 0.00, colors: 0.00, frags: 0.08, track: 1,
      hint: 'volume over trickery — ride the lane, keep the combo',
      bands: [{ t0: 28, t1: 44, intensity: 1.5 }],
      story: { line: 'The sealed archive is being scrubbed tonight.' },
      comms: [{ t: 6, s: 'CMD', m: 'the vault lane is live. hold it.' },
              { t: 20, s: 'TRACE', m: 'these interdictors know our sealed manifests.' },
              { t: 36, s: 'HAUL', m: 'sealed means six people. count them.' }],
      caseNote: 'CASE NOTE: the scrub list matches SEALED manifests. six suspects.' },
    { name: 'PATROL LOOP', tint: '255,160,80', duration: 55, spawnMin: 0.68, spawnMax: 1.20, speed: 0.49, doubles: 0.50, heavies: 0.10, lines: 0.00, colors: 0.00, frags: 0.10, track: 2, bursts: true,
      hint: 'the loop runs HOT — pure traffic, find your rhythm',
      bands: [{ t0: 16, t1: 32, intensity: 1.5 }, { t0: 44, t1: 53, intensity: 1.8 }],
      story: { line: 'The patrol loop knows who flew that night.' },
      comms: [{ t: 6, s: 'TRACE', m: 'pulling duty rosters off the loop.' },
              { t: 22, s: 'CMD', m: 'four of the six were on watch. narrow it.' },
              { t: 38, s: 'HAUL', m: 'and two of them signed the gateway PO.' }],
      caseNote: 'CASE NOTE: two signatures on the gateway purchase order.' },
    { name: 'INTERNAL AFFAIRS', tint: '120,230,190', duration: 60, spawnMin: 0.62, spawnMax: 1.10, speed: 0.52, doubles: 0.50, heavies: 0.10, lines: 0.00, colors: 0.15, frags: 0.12, track: 0,
      hint: 'phase locks in the flood — glance, match, keep moving',
      bands: [{ t0: 30, t1: 48, intensity: 1.6 }],
      story: { line: 'Internal Affairs opened a file. Then leaked.' },
      comms: [{ t: 6, s: 'CMD', m: 'IA is compromised. assume everything leaks.' },
              { t: 22, s: 'TRACE', m: 'keys cut from an IA terminal. inside again.' },
              { t: 38, s: 'CMD', m: 'clean hands. dirty terminal. noted.' }],
      caseNote: 'CASE NOTE: the IA leak runs through ONE terminal. logged.' },
    { name: 'SHELL EXCHANGE', tint: '255,205,90', duration: 60, spawnMin: 0.58, spawnMax: 1.00, speed: 0.55, doubles: 0.55, heavies: 0.12, lines: 0.00, colors: 0.15, frags: 0.12, track: 1, bursts: true,
      hint: 'burst volleys — the flood comes in waves now',
      bands: [{ t0: 24, t1: 42, intensity: 1.7, mix: { doubles: 0.6 } }],
      story: { line: 'Eleven shell charters. One drawer.' },
      comms: [{ t: 6, s: 'HAUL', m: 'eleven shells, one registered drawer.' },
              { t: 24, s: 'TRACE', m: 'volley pattern says: hiding ONE charge.' },
              { t: 40, s: 'CMD', m: 'find the charge they protect. follow it.' }],
      caseNote: 'CASE NOTE: one transfer matters. the rest is smoke.' },
    { name: 'LAUNDRY LANE', tint: '150,120,255', duration: 65, spawnMin: 0.55, spawnMax: 0.95, speed: 0.57, doubles: 0.55, heavies: 0.10, lines: 0.08, colors: 0.18, frags: 0.14, walls: 0.06, track: 2,
      hint: 'walls in the current — reroute without losing the beat',
      bands: [{ t0: 28, t1: 46, intensity: 1.6 }],
      story: { line: 'The money washes out past the old mint.' },
      comms: [{ t: 6, s: 'CMD', m: 'they wall the rail on every wash cycle.' },
              { t: 24, s: 'TRACE', m: 'mixer output pings a BLACKSITE relay.' },
              { t: 40, s: 'HAUL', m: 'a blacksite. of course it is.' }],
      caseNote: 'CASE NOTE: the wash empties into a blacksite relay.' },
    { name: 'BLACKSITE RELAY', tint: '255,90,110', duration: 70, spawnMin: 0.50, spawnMax: 0.90, speed: 0.60, doubles: 0.60, heavies: 0.14, lines: 0.08, colors: 0.18, frags: 0.16, walls: 0.08, track: 0, bursts: true,
      hint: 'blacksite pace — the fastest lane yet',
      bands: [{ t0: 26, t1: 44, intensity: 1.8 }, { t0: 56, t1: 66, intensity: 2.0 }],
      story: { line: 'A relay on no chart, built with real money.' },
      comms: [{ t: 6, s: 'TRACE', m: 'this hardware matches the gateway spec.' },
              { t: 26, s: 'CMD', m: 'same foundry. same mark. same hand.' },
              { t: 44, s: 'HAUL', m: 'the paymaster built BOTH. find him.' }],
      caseNote: 'CASE NOTE: gateway and blacksite share one paymaster.' },
    { name: 'THE PAYMASTER', tint: '255,70,160', duration: 75, spawnMin: 0.48, spawnMax: 0.85, speed: 0.63, doubles: 0.60, heavies: 0.15, lines: 0.10, colors: 0.20, frags: 0.18, walls: 0.08, track: 1, bursts: true,
      hint: 'his ledger floods the lane — survive the torrent',
      bands: [{ t0: 18, t1: 38, intensity: 1.7 }, { t0: 52, t1: 70, intensity: 2.1, mix: { doubles: 0.65 } }],
      story: { line: 'One retired clearance signs every invoice.' },
      comms: [{ t: 6, s: 'CMD', m: 'a retired clearance signing live invoices.' },
              { t: 28, s: 'TRACE', m: 'ledger sync begins. hold the intercept.' },
              { t: 48, s: 'HAUL', m: 'he knows we are reading. he is proud.' }],
      caseNote: 'CASE NOTE: the ledger names every buyer. one clearance signs.' },
    { name: 'BADGE ZERO', tint: '212,101,255', duration: 50, spawnMin: 0.70, spawnMax: 1.25, speed: 0.55, doubles: 0.45, heavies: 0.16, lines: 0.10, colors: 0.22, frags: 0.14, walls: 0.08, track: 2, boss: true, bossKind: 'triad',
      hint: 'his private warden is THREE — shield, shredder, alibi. break each',
      story: { line: 'He cast a private warden from stolen plans.' },
      comms: [{ t: 4, s: 'WARD', m: 'my maker is untouchable. so am I.' },
              { t: 16, s: 'CMD', m: 'three heads, one snake. take them all.' }],
      caseNote: 'CASE CLOSED: badge zero indicted. the ladder is ash.' }
  ],
  verdict: { title: 'LOG 18 — THE LADDER', lines: [
    'The private warden burned with the', 'ledger open. Every name on it was',
    'served by morning — badge zero', 'first. The lane is finally quiet.'] }
},
{
  id: 'signal-lost', format: 1,
  title: 'DEEP SPACE', tagline: 'SIGNAL LOST · THE DEAD REACH', difficulty: 3,
  story: 'Badge Zero is served — and a whole relay chain out along the reach goes dark overnight. No breach, no ransom, just silence. Its automated defences still run with no master, and something has re-lit the dead beacon at the end of the lane.',
  map: { theme: 'chart' },
  speakers: [
    { id: 'HAUL',  name: 'Meridian Haulage', color: '111,227,255', portrait: { drawn: 'HAUL' } },
    { id: 'CMD',   name: 'Lane Command', color: '235,245,255', portrait: { drawn: 'CMD' } },
    { id: 'TRACE', name: 'Lane Command trace analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'WARD',  name: 'the beacon', color: '255,230,120', portrait: { drawn: 'WARD' } }
  ],
  levels: [
    { name: 'DEAD HARBOR', tint: '80,200,215', duration: 55, spawnMin: 1.00, spawnMax: 1.65, speed: 0.48, doubles: 0.30, heavies: 0.18, lines: 0.30, colors: 0.35, frags: 0.10, track: 0,
      hint: 'a dead lane — every interdictor here was left ON PURPOSE',
      story: { line: 'A whole chain out on the reach went dark overnight.' },
      comms: [{ t: 6, s: 'CMD', m: 'the reach is dark. all of it.' },
              { t: 22, s: 'TRACE', m: 'defences live, crews gone. eerie.' },
              { t: 40, s: 'HAUL', m: 'who mines a lane nobody flies?' }],
      caseNote: 'CASE NOTE: the reach went dark on a SCHEDULE. planned silence.' },
    { name: 'GHOST CURRENT', tint: '110,225,170', duration: 55, spawnMin: 0.60, spawnMax: 1.00, speed: 0.58, doubles: 0.60, heavies: 0.06, lines: 0.00, colors: 0.00, frags: 0.10, track: 1, bursts: true,
      hint: 'the current still runs — fast, blind, and full',
      bands: [{ t0: 15, t1: 30, intensity: 1.7 }, { t0: 40, t1: 52, intensity: 1.9 }],
      story: { line: 'Traffic with no sender. Something eats it.' },
      comms: [{ t: 6, s: 'TRACE', m: 'traffic with no sender. recorded loops.' },
              { t: 24, s: 'HAUL', m: 'a dead lane that will not die.' },
              { t: 44, s: 'CMD', m: 'ride it. see where it drains.' }],
      caseNote: 'CASE NOTE: the ghost traffic drains toward the old beacon hub.' },
    { name: 'CIPHER SHOALS', tint: '255,190,110', duration: 60, spawnMin: 0.95, spawnMax: 1.50, speed: 0.50, doubles: 0.35, heavies: 0.20, lines: 0.28, colors: 0.45, frags: 0.14, walls: 0.12, track: 2,
      hint: 'shoal water — phase-locked reefs and sealed pairs, read before you steer',
      beats: [{ t: 26, kind: 'wall' }, { t: 35, kind: 'strip' }, { t: 46, kind: 'wall' }],
      story: { line: 'The shoals are mined with keys still turning.' },
      comms: [{ t: 6, s: 'CMD', m: 'old keys, still turning. mind the phases.' },
              { t: 20, s: 'TRACE', m: 'these locks predate badge zero. YEARS old.' },
              { t: 38, s: 'HAUL', m: 'then who has been winding them?' }],
      caseNote: 'CASE NOTE: the shoal locks are OLDER than the corruption case.' },
    { name: 'RIPTIDE', tint: '120,160,255', duration: 60, spawnMin: 0.55, spawnMax: 0.92, speed: 0.60, doubles: 0.65, heavies: 0.05, lines: 0.00, colors: 0.00, frags: 0.12, track: 0, bursts: true,
      hint: 'riptide — do not fight the pace, become it',
      bands: [{ t0: 12, t1: 28, intensity: 1.8 }, { t0: 36, t1: 54, intensity: 2.0, mix: { doubles: 0.7 } }],
      story: { line: 'The drain pulls harder the closer we get.' },
      comms: [{ t: 6, s: 'HAUL', m: 'flow rate doubled. tripled. keep up.' },
              { t: 30, s: 'CMD', m: 'steady hands. it wants you rushed.' }],
      caseNote: 'CASE NOTE: the drain pulls harder the closer we get.' },
    { name: 'THE SHALLOWS', tint: '150,230,120', duration: 65, spawnMin: 0.90, spawnMax: 1.42, speed: 0.52, doubles: 0.35, heavies: 0.22, lines: 0.30, colors: 0.40, frags: 0.16, walls: 0.18, track: 1,
      hint: 'the rail closes in shallow water — plan two moves ahead',
      beats: [{ t: 24, kind: 'wall' }, { t: 40, kind: 'lull', dur: 5 }, { t: 52, kind: 'wall' }],
      story: { line: 'Hulks everywhere, killed by their own walls.' },
      comms: [{ t: 6, s: 'TRACE', m: 'wall scars on every hulk out here.' },
              { t: 20, s: 'CMD', m: 'this is a training ground. WAS.' },
              { t: 46, s: 'HAUL', m: 'so the beacon had a teacher once.' }],
      caseNote: 'CASE NOTE: the hulks are practice targets. YEARS of drills.' },
    { name: 'UNDERTOW', tint: '255,120,140', duration: 70, spawnMin: 0.50, spawnMax: 0.86, speed: 0.63, doubles: 0.65, heavies: 0.12, lines: 0.00, colors: 0.00, frags: 0.18, track: 2, bursts: true,
      hint: 'undertow — the fastest water on the dead reach',
      bands: [{ t0: 14, t1: 34, intensity: 1.8 }, { t0: 46, t1: 64, intensity: 2.2 }],
      story: { line: 'A second current runs the other way.' },
      comms: [{ t: 6, s: 'CMD', m: 'it reads us as we ride. shield nothing.' },
              { t: 38, s: 'TRACE', m: 'copies of OUR traffic in the drain.' }],
      caseNote: 'CASE NOTE: the beacon has been listening since relay one.' },
    { name: 'THE NARROWS', tint: '210,140,255', duration: 75, spawnMin: 0.58, spawnMax: 0.98, speed: 0.58, doubles: 0.50, heavies: 0.22, lines: 0.26, colors: 0.40, frags: 0.20, walls: 0.18, track: 0, bursts: true,
      hint: 'the narrows: every trick on the reach, then open water',
      beats: [{ t: 31, kind: 'wall' }, { t: 50, kind: 'wall' }, { t: 62, kind: 'strip' }],
      bands: [{ t0: 34, t1: 48, intensity: 1.9 }],
      story: { line: 'One channel left, and it is everything.' },
      comms: [{ t: 6, s: 'HAUL', m: 'it is WAITING for us now.' },
              { t: 26, s: 'TRACE', m: 'signal ahead. clean. an invitation.' },
              { t: 54, s: 'CMD', m: 'accept it. emitters hot.' }],
      caseNote: 'CASE NOTE: it let us through. it wanted an audience.' },
    { name: 'THE BEACON', tint: '255,230,120', duration: 50, spawnMin: 0.80, spawnMax: 1.40, speed: 0.55, doubles: 0.35, heavies: 0.18, lines: 0.20, colors: 0.30, frags: 0.14, walls: 0.10, track: 1, boss: true, bossKind: 'spinner',
      hint: 'ride the light — survive every sweep and the beacon burns itself out',
      story: { line: 'A light built to guide, guiding still.' },
      comms: [{ t: 4, s: 'WARD', m: 'i kept the light on. where were you?' },
              { t: 16, s: 'CMD', m: 'ride the beam, runner. let it spend itself.' }],
      caseNote: 'CASE CLOSED: the light is out. the reach sleeps quiet.' }
  ],
  verdict: { title: 'LOG 27 — LIGHTS OUT', lines: [
    'The beacon burned through its own', 'charge and went dark for good. The',
    'reach came back online by morning.', 'Somewhere, a new case is waiting.'] }
},
{
  id: 'the-bait', format: 1,
  title: 'OUTLAW TERRITORY', tagline: 'THE BAIT · FLUSH THE DISPATCHER', difficulty: 4,
  story: 'Every dead lane traced back to one hand that never shows itself — the dispatcher who cast the gateway, the blacksite, and the beacon, and never once flew a lane. You cannot trace something that only ever transmits outward. So we stop chasing and start fishing: the cargo you escort now is BAIT, dressed as the evidence he burns for, phased to the locks his hunters cannot resist.',
  map: { theme: 'chart' },
  speakers: [
    { id: 'HAUL',  name: 'Meridian Haulage', color: '111,227,255', portrait: { drawn: 'HAUL' } },
    { id: 'CMD',   name: 'Lane Command', color: '235,245,255', portrait: { drawn: 'CMD' } },
    { id: 'TRACE', name: 'Lane Command trace analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'WARD',  name: 'the Dispatcher’s hunter', color: '212,120,255', portrait: { drawn: 'WARD' } }
  ],
  levels: [
    { name: 'DECOY RELAY', tint: '255,190,90', duration: 45, spawnMin: 0.90, spawnMax: 1.45, speed: 0.52, doubles: 0.35, heavies: 0.12, lines: 0.10, colors: 0.35, frags: 0.10, track: 0,
      hint: 'the cargo is BAIT now — dress it in his phases, make him bite',
      story: { line: 'He never transmits inward. So we set out bait.' },
      comms: [{ t: 6, s: 'CMD', m: 'stop chasing. we fish now. bait is live.' },
              { t: 20, s: 'TRACE', m: 'decoy dressed as the sealed manifest.' },
              { t: 34, s: 'HAUL', m: 'if he wants it, he comes to us.' }],
      caseNote: 'CASE NOTE: the bait is in the lane. now we wait for a bite.' },
    { name: 'HONEYLANE', tint: '126,200,110', duration: 50, spawnMin: 0.80, spawnMax: 1.32, speed: 0.55, doubles: 0.40, heavies: 0.14, lines: 0.12, colors: 0.45, frags: 0.12, track: 1,
      hint: 'match the bait to the mark — wrong phase, no bite',
      bands: [{ t0: 26, t1: 44, intensity: 1.5 }],
      story: { line: 'The first probes arrive, gloved and picky.' },
      comms: [{ t: 6, s: 'TRACE', m: 'probes sniffing the decoy. keyed, picky.' },
              { t: 24, s: 'HAUL', m: 'they bite their own phase. feed them.' },
              { t: 40, s: 'CMD', m: 'good. he thinks the manifest is real.' }],
      caseNote: 'CASE NOTE: the hunters are phase-keyed. each bites one lure.' },
    { name: 'MIRROR VAULT', tint: '90,200,235', duration: 55, spawnMin: 0.70, spawnMax: 1.18, speed: 0.58, doubles: 0.45, heavies: 0.14, lines: 0.14, colors: 0.50, frags: 0.12, walls: 0.06, track: 2, bursts: true,
      hint: 'the bite comes in volleys now — hold your phases steady',
      bands: [{ t0: 18, t1: 36, intensity: 1.6 }],
      beats: [{ t: 30, kind: 'strip' }],
      story: { line: 'He cracked a vault of counterfeit manifests.' },
      comms: [{ t: 6, s: 'CMD', m: 'he breached the mirror. it is all decoy.' },
              { t: 24, s: 'TRACE', m: 'volleys now — he committed real hunters.' },
              { t: 42, s: 'HAUL', m: 'and real hunters have a home berth.' }],
      caseNote: 'CASE NOTE: his hunters carry a return vector. TRACE has it.' },
    { name: 'CHUM RUN', tint: '255,150,70', duration: 60, spawnMin: 0.62, spawnMax: 1.05, speed: 0.60, doubles: 0.50, heavies: 0.16, lines: 0.16, colors: 0.45, frags: 0.14, walls: 0.08, track: 0, bursts: true,
      hint: 'blood in the water — the whole pack answers at once',
      bands: [{ t0: 22, t1: 40, intensity: 1.7, mix: { colors: 0.6 } }],
      story: { line: 'We spill the whole cache. The pack feeds.' },
      comms: [{ t: 6, s: 'HAUL', m: 'chum is out. every hunter he owns turned.' },
              { t: 26, s: 'TRACE', m: 'mapping each one back as it bites.' },
              { t: 44, s: 'CMD', m: 'he taught them to feed, not think.' }],
      caseNote: 'CASE NOTE: the pack maps to ONE upstream warden. we have him.' },
    { name: 'TRACEBACK', tint: '120,160,255', duration: 60, spawnMin: 0.56, spawnMax: 0.96, speed: 0.63, doubles: 0.50, heavies: 0.18, lines: 0.18, colors: 0.50, frags: 0.16, walls: 0.10, track: 1,
      hint: 'follow the bite home — phase-locked traffic all the way down',
      bands: [{ t0: 28, t1: 48, intensity: 1.7 }],
      story: { line: 'Every hunter reels home to one dark relay.' },
      comms: [{ t: 6, s: 'TRACE', m: 'riding the pack home. his keys, his doors.' },
              { t: 26, s: 'CMD', m: 'he lets his own hunters in. so do we.' },
              { t: 46, s: 'HAUL', m: 'closer. i can feel him watching.' }],
      caseNote: 'CASE NOTE: the traceback holds. the dispatcher has a door.' },
    { name: 'THE APIARY', tint: '255,205,90', duration: 65, spawnMin: 0.52, spawnMax: 0.90, speed: 0.65, doubles: 0.55, heavies: 0.18, lines: 0.20, colors: 0.55, frags: 0.18, walls: 0.12, track: 2, bursts: true,
      hint: 'the nest — every phase at once, and it is awake',
      bands: [{ t0: 20, t1: 38, intensity: 1.8 }, { t0: 50, t1: 63, intensity: 2.0, mix: { colors: 0.65 } }],
      story: { line: 'His hive: every hunter he ever cast.' },
      comms: [{ t: 6, s: 'CMD', m: 'the nest. every hunter he ever cast.' },
              { t: 26, s: 'TRACE', m: 'they know the bait was a hook. hot now.' },
              { t: 48, s: 'HAUL', m: 'hold. he always answers his hive.' }],
      caseNote: 'CASE NOTE: the hive is his. he will surface to defend it.' },
    { name: 'OPEN LANE', tint: '255,90,110', duration: 70, spawnMin: 0.48, spawnMax: 0.82, speed: 0.68, doubles: 0.58, heavies: 0.22, lines: 0.22, colors: 0.50, frags: 0.20, walls: 0.15, track: 0, bursts: true,
      hint: 'he has committed everything — this is the whole swarm',
      bands: [{ t0: 16, t1: 36, intensity: 1.9 }, { t0: 50, t1: 68, intensity: 2.1, mix: { colors: 0.6, doubles: 0.65 } }],
      story: { line: 'To save the hive, he opens a lane himself.' },
      comms: [{ t: 6, s: 'TRACE', m: 'a live signature. HIS. first one ever.' },
              { t: 28, s: 'HAUL', m: 'the bait worked. he blinked. hold on.' },
              { t: 50, s: 'CMD', m: 'lock the trace. we finish this next.' }],
      caseNote: 'CASE NOTE: the dispatcher transmitted. we have his core.' },
    { name: 'THE HUNTER', tint: '212,120,255', duration: 50, spawnMin: 0.72, spawnMax: 1.28, speed: 0.60, doubles: 0.45, heavies: 0.20, lines: 0.18, colors: 0.40, frags: 0.16, walls: 0.10, track: 1, boss: true, bossKind: 'triad',
      hint: 'his hunter-warden is THREE — the nose, the jaws, the ghost',
      story: { line: 'He sends his masterpiece to clean up.' },
      comms: [{ t: 4, s: 'WARD', m: 'clever bait. i taught them to bite. not me.' },
              { t: 16, s: 'CMD', m: 'three heads. nose, jaws, and tail. all of it.' }],
      caseNote: 'CASE CLOSED: the hunter is scrap. the dispatcher is exposed.' }
  ],
  verdict: { title: 'LOG 36 — THE VECTOR', lines: [
    'The hunter died in three pieces and', 'the dispatcher went silent — but too',
    'late. One live signature was all we', 'needed. We know where his core sits.'] }
},
{
  id: 'shutdown', format: 1,
  title: 'NO MANS LAND', tagline: 'SHUTDOWN · UNWRITE THE DISPATCHER', difficulty: 5,
  story: 'The dispatcher has a core, and now we have its bearing. There is no arrest for something that never existed on paper — only a shutdown. Meridian Haulage hands you the last cargo you will ever escort: an antidote, written to unwrite his entire operation. Run it down his lane to his core. He knows it is coming, and everything he has left stands between it and the door.',
  map: { theme: 'chart' },
  speakers: [
    { id: 'HAUL',  name: 'Meridian Haulage', color: '111,227,255', portrait: { drawn: 'HAUL' } },
    { id: 'CMD',   name: 'Lane Command', color: '235,245,255', portrait: { drawn: 'CMD' } },
    { id: 'TRACE', name: 'Lane Command trace analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'WARD',  name: 'the Dispatcher', color: '212,101,255', portrait: { drawn: 'WARD' } }
  ],
  levels: [
    { name: 'INJECTION POINT', tint: '96,180,255', duration: 50, spawnMin: 0.72, spawnMax: 1.20, speed: 0.58, doubles: 0.50, heavies: 0.15, lines: 0.20, colors: 0.30, frags: 0.15, walls: 0.10, track: 0,
      hint: 'you escort the antidote now — get it into his lane and hold on',
      story: { line: 'No warrant reaches him. Only this.' },
      comms: [{ t: 6, s: 'HAUL', m: 'cargo is live and it is lethal. mind it.' },
              { t: 20, s: 'CMD', m: 'this ends it. get it to his door intact.' },
              { t: 34, s: 'WARD', m: 'i see what you are carrying. turn back.' }],
      caseNote: 'CASE NOTE: the antidote is in his lane. he already knows.' },
    { name: 'THE GAUNTLET', tint: '255,160,80', duration: 55, spawnMin: 0.60, spawnMax: 1.02, speed: 0.63, doubles: 0.55, heavies: 0.16, lines: 0.22, colors: 0.32, frags: 0.16, walls: 0.12, track: 1, bursts: true,
      hint: 'his outer cordon throws everything — do not slow the convoy',
      bands: [{ t0: 18, t1: 36, intensity: 1.7 }],
      story: { line: 'His defences hunt the thing in your hold.' },
      comms: [{ t: 6, s: 'TRACE', m: 'defences full-live. he stopped pretending.' },
              { t: 24, s: 'HAUL', m: 'they want the cargo, not you. shield it.' },
              { t: 44, s: 'WARD', m: 'you carry your own death in there.' }],
      caseNote: 'CASE NOTE: his lane is all-in on stopping ONE hull. ours.' },
    { name: 'CORDON DELTA', tint: '120,230,190', duration: 60, spawnMin: 0.54, spawnMax: 0.92, speed: 0.66, doubles: 0.55, heavies: 0.18, lines: 0.26, colors: 0.35, frags: 0.18, walls: 0.18, track: 2,
      hint: 'walls stacked on walls — thread the convoy through, do not clip it',
      beats: [{ t: 20, kind: 'wall' }, { t: 40, kind: 'wall' }, { t: 50, kind: 'strip' }],
      bands: [{ t0: 28, t1: 48, intensity: 1.7 }],
      story: { line: 'He is sealing the antidote in a dead segment.' },
      comms: [{ t: 6, s: 'CMD', m: 'he is walling it into a pocket. break out.' },
              { t: 26, s: 'TRACE', m: 'do not let the convoy stall in a dead cell.' },
              { t: 46, s: 'WARD', m: 'quarantine holding. you cannot reach me.' }],
      caseNote: 'CASE NOTE: he cannot kill the antidote — only try to trap it.' },
    { name: 'THE SCREAMING LANE', tint: '255,205,90', duration: 60, spawnMin: 0.50, spawnMax: 0.86, speed: 0.69, doubles: 0.60, heavies: 0.20, lines: 0.24, colors: 0.38, frags: 0.20, walls: 0.16, track: 0, bursts: true,
      hint: 'pure panic traffic — become the pace or drown in it',
      bands: [{ t0: 14, t1: 32, intensity: 1.9 }, { t0: 42, t1: 58, intensity: 2.1, mix: { doubles: 0.7 } }],
      story: { line: 'He fires decades of tricks at once, blind.' },
      comms: [{ t: 6, s: 'HAUL', m: 'flow is off the chart. he is panicking.' },
              { t: 30, s: 'CMD', m: 'steady. a panicked cordon has holes.' },
              { t: 52, s: 'WARD', m: 'stop. STOP. you do not know what i built.' }],
      caseNote: 'CASE NOTE: the dispatcher is out of plans. only noise left.' },
    { name: 'QUARANTINE', tint: '150,120,255', duration: 65, spawnMin: 0.46, spawnMax: 0.80, speed: 0.72, doubles: 0.60, heavies: 0.20, lines: 0.28, colors: 0.40, frags: 0.22, walls: 0.20, track: 1, bursts: true,
      hint: 'he seals every gate — keyed, walled, doubled. read fast',
      bands: [{ t0: 20, t1: 40, intensity: 1.9 }, { t0: 50, t1: 63, intensity: 2.2, mix: { colors: 0.55 } }],
      beats: [{ t: 34, kind: 'wall' }, { t: 48, kind: 'wall' }],
      story: { line: 'He falls back to the core and seals it.' },
      comms: [{ t: 6, s: 'TRACE', m: 'he is inside the last cordon. sealing it.' },
              { t: 28, s: 'HAUL', m: 'every gate keyed AND walled. thread it.' },
              { t: 50, s: 'WARD', m: 'i can hold this door forever. try me.' }],
      caseNote: 'CASE NOTE: one cordon left. then his core, and the antidote.' },
    { name: 'DEEP TRANSIT', tint: '255,90,110', duration: 70, spawnMin: 0.44, spawnMax: 0.76, speed: 0.75, doubles: 0.62, heavies: 0.22, lines: 0.26, colors: 0.42, frags: 0.22, walls: 0.20, track: 2, bursts: true,
      hint: 'the fastest water on any lane — do not fight it, ride it',
      bands: [{ t0: 16, t1: 36, intensity: 2.0 }, { t0: 48, t1: 68, intensity: 2.2, mix: { doubles: 0.7, colors: 0.55 } }],
      story: { line: 'Down here he has nothing left but speed.' },
      comms: [{ t: 6, s: 'HAUL', m: 'pace maxed. the convoy is still alive. go.' },
              { t: 36, s: 'CMD', m: 'almost on the core. do not lose it now.' },
              { t: 58, s: 'WARD', m: 'you are in my house. it will not save you.' }],
      caseNote: 'CASE NOTE: the antidote is intact and one cordon from the core.' },
    { name: 'THE THRESHOLD', tint: '255,70,160', duration: 75, spawnMin: 0.42, spawnMax: 0.72, speed: 0.78, doubles: 0.65, heavies: 0.25, lines: 0.28, colors: 0.45, frags: 0.25, walls: 0.22, track: 0, bursts: true,
      hint: 'everything he has, all at once, at full speed — the last door',
      bands: [{ t0: 18, t1: 38, intensity: 2.0 }, { t0: 52, t1: 72, intensity: 2.3, mix: { colors: 0.6, doubles: 0.72 } }],
      beats: [{ t: 34, kind: 'wall' }, { t: 62, kind: 'wall' }],
      story: { line: 'One narrow gate. Cross it and he ends.' },
      comms: [{ t: 6, s: 'CMD', m: 'last door. he threw it all on this one.' },
              { t: 30, s: 'TRACE', m: 'gap coming. the antidote only needs one.' },
              { t: 56, s: 'WARD', m: 'i cast all of it. you are NOTHING.' }],
      caseNote: 'CASE NOTE: threshold breached. the core is open. deliver it.' },
    { name: 'THE DISPATCHER', tint: '212,101,255', duration: 55, spawnMin: 0.68, spawnMax: 1.22, speed: 0.66, doubles: 0.50, heavies: 0.22, lines: 0.20, colors: 0.40, frags: 0.20, walls: 0.14, track: 1, boss: true, bossKind: 'core',
      hint: 'THE DISPATCHER — six injections seat the antidote and shut it down',
      story: { line: 'One quiet machine that never had a face.' },
      comms: [{ t: 4, s: 'WARD', m: 'i am every case you ever closed. you cannot—' },
              { t: 16, s: 'HAUL', m: 'seat it, runner. shut it down for good.' }],
      caseNote: 'CASE CLOSED: the dispatcher is unwritten. every lane goes quiet.' }
  ],
  verdict: { title: 'LOG 45 — CLEAR LANES', lines: [
    'The antidote seated and the dispatcher', 'unwrote itself, line by line — every',
    'dead case it ever cast going dark', 'behind it. The lanes are clear at last.'] }
}];
