// DATA DEFENDER: DARK FIBER — bundled campaign packages.
// One self-contained, JSON-shaped object per campaign (no functions): the
// exact format the Tunnel Designer exports and future community packages
// will use. Loaded before the game script; every package still passes
// validateCampaign() on install. See docs/CMS-ROADMAP.md.
const CAMPAIGN_PACKAGES = [{
  id: 'investigation', format: 1,
  title: 'THE INVESTIGATION', tagline: 'OMNISERVE HQ · POLICE CID', difficulty: 1,
  story: 'OmniServe HQ must deliver critical evidence to the CID across one fiber line. You are the hired defender who clears it, relay by relay, while the investigation uncovers who is trying to burn the evidence.',
  map: { theme: 'city' }, // procedural city; image maps carry { image, pins }
  speakers: [
    { id: 'OMNI',  name: 'OmniServe HQ', color: '111,227,255', portrait: { drawn: 'OMNI' } },
    { id: 'CID',   name: 'Cyber Investigations Dept', color: '235,245,255', portrait: { drawn: 'CID' } },
    { id: 'TRACE', name: 'CID tracer analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'CORE',  name: 'CID Gateway core', color: '212,101,255', portrait: { drawn: 'CORE' } }
  ],
  levels: [
    { name: 'OMNISERVE CAMPUS', tint: '80,160,255', duration: 40, spawnMin: 1.50, spawnMax: 2.30, speed: 0.34, doubles: 0.00, heavies: 0.00, lines: 0.00, colors: 0.00, track: 0,
      story: { title: 'LOG 01 — THE CONTRACT', lines: [
        'OmniServe HQ must deliver evidence', 'to the CID across one fiber line.',
        'You were hired to keep it clean.', 'Taps are already on the wire.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'payload staged. handshake nominal.' },
              { t: 16, s: 'CID', m: 'copy. evidence intake is open.' },
              { t: 28, s: 'OMNI', m: 'then who else is on this line?' }],
      caseNote: 'CASE NOTE: tap signatures logged. someone is listening.' },
    { name: 'OLD TOWN GRID', tint: '255,170,90', duration: 50, spawnMin: 1.05, spawnMax: 1.80, speed: 0.40, doubles: 0.30, heavies: 0.22, lines: 0.00, colors: 0.00, track: 1,
      hint: 'NEW THREAT: heavy armor — dock both nodes and HOLD',
      story: { title: 'LOG 02 — PATTERN', lines: [
        'These taps are not random noise.', 'Same make. Same timing.',
        'Someone wants the evidence gone.', 'The CID opens a case file.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'tap signatures match. one operator.' },
              { t: 20, s: 'CID', m: 'we are being read. keep transmitting.' },
              { t: 36, s: 'OMNI', m: 'the case files? someone knows.' }],
      caseNote: 'CASE NOTE: one operator confirmed. the CID opens a file.' },
    { name: 'METRO EXCHANGE', tint: '110,230,200', duration: 55, spawnMin: 0.95, spawnMax: 1.70, speed: 0.43, doubles: 0.30, heavies: 0.22, lines: 0.00, colors: 0.00, frags: 0.12, track: 2, bursts: true,
      hint: 'NEW THREAT: burst transmissions — traps arrive in volleys',
      story: { title: 'LOG 03 — TRAPS', lines: [
        'Volleys now — probing our reflexes.', 'And they seeded the line with',
        'NODE KILLERS: black traps that fry', 'any node that touches them.'] },
      comms: [{ t: 6, s: 'CID', m: 'black packets are node killers. do not touch.' },
              { t: 22, s: 'OMNI', m: 'who plants traps inside a live line?' },
              { t: 36, s: 'CID', m: 'someone who knows how we defend it.' }],
      caseNote: 'CASE NOTE: recovered node killers are factory-made.' },
    { name: 'HARBOR CROSSING', tint: '70,205,235', duration: 60, spawnMin: 0.85, spawnMax: 1.55, speed: 0.46, doubles: 0.35, heavies: 0.20, lines: 0.20, colors: 0.00, frags: 0.13, track: 0,
      hint: 'NEW THREAT: barrier lines — one node on each end',
      story: { title: 'LOG 04 — THE HARBOR', lines: [
        'Barrier taps under the harbor mud —', 'walls strung to catch the payload',
        'whole. Cutting a subsea line takes', 'resources. This is no lone hacker.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'barrier debris under the harbor mud.' },
              { t: 20, s: 'OMNI', m: 'a subsea cut needs a crew and money.' },
              { t: 36, s: 'CID', m: 'or a badge.' }],
      caseNote: 'CASE NOTE: a subsea cut takes resources. or a badge.' },
    { name: 'UNDERCITY FIBER', tint: '150,110,255', duration: 60, spawnMin: 0.72, spawnMax: 1.35, speed: 0.46, doubles: 0.40, heavies: 0.20, lines: 0.20, colors: 0.00, frags: 0.14, walls: 0.10, track: 1,
      hint: 'NEW THREAT: rim walls — the rail closes, route around',
      story: { title: 'LOG 05 — UNDERCITY', lines: [
        'They chain their traps now — walls', 'of them, sealing whole sections of',
        'the rail. We traced the deployment', 'key: it holds CID clearance.'] },
      comms: [{ t: 6, s: 'CID', m: 'they are walling the rail. reroute.' },
              { t: 20, s: 'TRACE', m: 'deployment key holds active clearance.' },
              { t: 34, s: 'CID', m: 'log it. tell no one.' }],
      caseNote: 'CASE NOTE: the wall deployment key holds active clearance.' },
    { name: 'FINANCIAL SPINE', tint: '255,205,80', duration: 65, spawnMin: 0.68, spawnMax: 1.25, speed: 0.48, doubles: 0.42, heavies: 0.18, lines: 0.18, colors: 0.40, frags: 0.16, walls: 0.10, track: 2,
      hint: 'NEW THREAT: color-locked traps — match the node color',
      story: { title: 'LOG 06 — CREDENTIALS', lines: [
        'Keyed taps — cut with CURRENT keys,', 'rotated this very morning. Whoever',
        'hunts this line holds live clearance.', 'OMNI or CID. Trust no one.'] },
      comms: [{ t: 6, s: 'CID', m: 'rotate all credentials. now.' },
              { t: 20, s: 'TRACE', m: 'locks cut with keys rotated TODAY.' },
              { t: 36, s: 'OMNI', m: 'inside. it is someone inside.' }],
      caseNote: 'CASE NOTE: keys rotated TODAY. the leak is inside.' },
    { name: 'DARKNET EDGE', tint: '255,70,100', duration: 70, spawnMin: 0.58, spawnMax: 1.10, speed: 0.54, doubles: 0.48, heavies: 0.22, lines: 0.22, colors: 0.36, frags: 0.20, walls: 0.15, track: 0, bursts: true,
      hint: 'ALL THREATS ACTIVE — maximum traffic',
      story: { title: 'LOG 07 — SIGNATURE', lines: [
        'Every tap signature matches one', 'system: the CID GATEWAY itself.',
        'The firewall meant to receive the', 'evidence is burning it instead.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'signature isolated: CID GATEWAY core.' },
              { t: 20, s: 'OMNI', m: 'the receiver is the thief.' },
              { t: 36, s: 'CID', m: '…purge authorized. deliver it.' }],
      caseNote: 'CASE NOTE: signature match — CID GATEWAY. purge authorized.' },
    { name: 'CID GATEWAY', tint: '212,101,255', duration: 45, spawnMin: 0.80, spawnMax: 1.40, speed: 0.50, doubles: 0.35, heavies: 0.20, lines: 0.20, colors: 0.30, frags: 0.15, walls: 0.10, track: 2, boss: true,
      hint: 'THE FIREWALL CORE AWAITS — six bolts close the case',
      story: { title: 'LOG 08 — THE GATEWAY', lines: [
        'The gateway core was turned — bought', 'to keep the evidence out of court.',
        'Purge it, deliver the payload,', 'and close the case.'] },
      comms: [{ t: 4, s: 'CORE', m: 'the evidence is contaminated. I am the cure.' },
              { t: 16, s: 'CID', m: 'burn it out, defender. close the case.' }],
      caseNote: 'CASE CLOSED: gateway purged. evidence delivered.' }
  ],
  verdict: { title: 'LOG 09 — VERDICT', lines: [
    'The gateway burned. The payload', 'reached the CID intact. Warrants',
    'went out within the hour — the', 'buyer wore a badge. Case closed.'] }
},
{
  id: 'going-deeper', format: 1,
  title: 'GOING DEEPER', tagline: 'THE CORRUPTION CASE', difficulty: 2,
  story: 'The gateway burned and a buyer wore a badge — but a badge takes orders. Someone above the arrest is still burning evidence, and every wire you defend digs one layer closer to whoever is behind the corruption.',
  map: { theme: 'city' },
  speakers: [
    { id: 'OMNI',  name: 'OmniServe HQ', color: '111,227,255', portrait: { drawn: 'OMNI' } },
    { id: 'CID',   name: 'Cyber Investigations Dept', color: '235,245,255', portrait: { drawn: 'CID' } },
    { id: 'TRACE', name: 'CID tracer analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'CORE',  name: 'an unregistered core', color: '212,101,255', portrait: { drawn: 'CORE' } }
  ],
  levels: [
    { name: 'EVIDENCE VAULT', tint: '96,180,255', duration: 50, spawnMin: 0.75, spawnMax: 1.30, speed: 0.46, doubles: 0.45, heavies: 0.08, lines: 0.00, colors: 0.00, frags: 0.08, track: 1,
      hint: 'volume over trickery — ride the stream, keep the combo',
      bands: [{ t0: 28, t1: 44, intensity: 1.5 }],
      story: { title: 'LOG 10 — REOPENED', lines: [
        'The buyer wore a badge. He also', 'took orders. Tonight the sealed',
        'case archive is being scrubbed —', 'someone above him is still awake.'] },
      comms: [{ t: 6, s: 'CID', m: 'the vault line is live. hold it.' },
              { t: 20, s: 'TRACE', m: 'these taps know our sealed filenames.' },
              { t: 36, s: 'OMNI', m: 'sealed means six people. count them.' }],
      caseNote: 'CASE NOTE: the scrub list matches SEALED files. six suspects.' },
    { name: 'PRECINCT LOOP', tint: '255,160,80', duration: 55, spawnMin: 0.68, spawnMax: 1.20, speed: 0.49, doubles: 0.50, heavies: 0.10, lines: 0.00, colors: 0.00, frags: 0.10, track: 2, bursts: true,
      hint: 'the loop runs HOT — pure traffic, find your rhythm',
      bands: [{ t0: 16, t1: 32, intensity: 1.5 }, { t0: 44, t1: 53, intensity: 1.8 }],
      story: { title: 'LOG 11 — THE LOOP', lines: [
        'We tapped the precinct intranet.', 'Whoever burns evidence files their',
        'overtime on this loop. Defend the', 'wire while TRACE reads the badges.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'pulling duty rosters off the loop.' },
              { t: 22, s: 'CID', m: 'four of the six were on shift. narrow it.' },
              { t: 38, s: 'OMNI', m: 'and two of them signed the gateway PO.' }],
      caseNote: 'CASE NOTE: two signatures on the gateway purchase order.' },
    { name: 'INTERNAL AFFAIRS', tint: '120,230,190', duration: 60, spawnMin: 0.62, spawnMax: 1.10, speed: 0.52, doubles: 0.50, heavies: 0.10, lines: 0.00, colors: 0.15, frags: 0.12, track: 0,
      hint: 'keyed taps in the flood — glance, match, keep moving',
      bands: [{ t0: 30, t1: 48, intensity: 1.6 }],
      story: { title: 'LOG 12 — CLEAN HANDS', lines: [
        'Internal Affairs opened their own', 'file — then their line lit up with',
        'keyed taps cut from IA credentials.', 'The watchers are being watched.'] },
      comms: [{ t: 6, s: 'CID', m: 'IA is compromised. assume everything leaks.' },
              { t: 22, s: 'TRACE', m: 'keys cut from an IA terminal. inside again.' },
              { t: 38, s: 'CID', m: 'clean hands. dirty terminal. noted.' }],
      caseNote: 'CASE NOTE: the IA leak runs through ONE terminal. logged.' },
    { name: 'SHELL EXCHANGE', tint: '255,205,90', duration: 60, spawnMin: 0.58, spawnMax: 1.00, speed: 0.55, doubles: 0.55, heavies: 0.12, lines: 0.00, colors: 0.15, frags: 0.12, track: 1, bursts: true,
      hint: 'burst volleys — the flood comes in waves now',
      bands: [{ t0: 24, t1: 42, intensity: 1.7, mix: { doubles: 0.6 } }],
      story: { title: 'LOG 13 — PAPER WALLS', lines: [
        'The gateway money moved through', 'shell companies — eleven names,',
        'one drawer. They flood the line', 'with noise to bury one transfer.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'eleven shells, one registered drawer.' },
              { t: 24, s: 'TRACE', m: 'volley pattern says: hiding ONE packet.' },
              { t: 40, s: 'CID', m: 'find the packet they protect. follow it.' }],
      caseNote: 'CASE NOTE: one transfer matters. the rest is smoke.' },
    { name: 'LAUNDRY LINE', tint: '150,120,255', duration: 65, spawnMin: 0.55, spawnMax: 0.95, speed: 0.57, doubles: 0.55, heavies: 0.10, lines: 0.08, colors: 0.18, frags: 0.14, walls: 0.06, track: 2,
      hint: 'walls in the current — reroute without losing the beat',
      bands: [{ t0: 28, t1: 46, intensity: 1.6 }],
      story: { title: 'LOG 14 — THE WASH', lines: [
        'The transfer washes through a', 'crypto mixer under the old mint.',
        'They wall the rail while value', 'moves. Route around. Stay on it.'] },
      comms: [{ t: 6, s: 'CID', m: 'they wall the rail on every wash cycle.' },
              { t: 24, s: 'TRACE', m: 'mixer output pings a BLACKSITE relay.' },
              { t: 40, s: 'OMNI', m: 'a blacksite. of course it is.' }],
      caseNote: 'CASE NOTE: the wash empties into a blacksite relay.' },
    { name: 'BLACKSITE RELAY', tint: '255,90,110', duration: 70, spawnMin: 0.50, spawnMax: 0.90, speed: 0.60, doubles: 0.60, heavies: 0.14, lines: 0.08, colors: 0.18, frags: 0.16, walls: 0.08, track: 0, bursts: true,
      hint: 'blacksite pace — the fastest line yet',
      bands: [{ t0: 26, t1: 44, intensity: 1.8 }, { t0: 56, t1: 66, intensity: 2.0 }],
      story: { title: 'LOG 15 — OFF THE BOOKS', lines: [
        'The relay is not on any network', 'map. Government-grade hardware,',
        'zero paperwork. Nobody builds a', 'blacksite for one dirty badge.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'this hardware matches the gateway spec.' },
              { t: 26, s: 'CID', m: 'same vendor. same signature. same hand.' },
              { t: 44, s: 'OMNI', m: 'the paymaster built BOTH. find him.' }],
      caseNote: 'CASE NOTE: gateway and blacksite share one paymaster.' },
    { name: 'THE PAYMASTER', tint: '255,70,160', duration: 75, spawnMin: 0.48, spawnMax: 0.85, speed: 0.63, doubles: 0.60, heavies: 0.15, lines: 0.10, colors: 0.20, frags: 0.18, walls: 0.08, track: 1, bursts: true,
      hint: 'his ledger floods the line — survive the torrent',
      bands: [{ t0: 18, t1: 38, intensity: 1.7 }, { t0: 52, t1: 70, intensity: 2.1, mix: { doubles: 0.65 } }],
      story: { title: 'LOG 16 — THE LEDGER', lines: [
        'A name signs every invoice: a', 'commissioner-level login, retired',
        'on paper for six years. His ledger', 'syncs tonight. Take the line.'] },
      comms: [{ t: 6, s: 'CID', m: 'a retired login signing live invoices.' },
              { t: 28, s: 'TRACE', m: 'ledger sync begins. defend the intercept.' },
              { t: 48, s: 'OMNI', m: 'he knows we are reading. he is proud.' }],
      caseNote: 'CASE NOTE: the ledger names every buyer. one login signs.' },
    { name: 'BADGE ZERO', tint: '212,101,255', duration: 50, spawnMin: 0.70, spawnMax: 1.25, speed: 0.55, doubles: 0.45, heavies: 0.16, lines: 0.10, colors: 0.22, frags: 0.14, walls: 0.08, track: 2, boss: true, bossKind: 'triad',
      hint: 'his private core is THREE — shield, shredder, alibi. break each',
      story: { title: 'LOG 17 — BADGE ZERO', lines: [
        'He built himself a private core', 'from the stolen gateway schematics',
        '— his shield, his shredder, his', 'alibi. Burn it. End the ladder.'] },
      comms: [{ t: 4, s: 'CORE', m: 'my maker is untouchable. so am I.' },
              { t: 16, s: 'CID', m: 'three heads, one snake. take them all.' }],
      caseNote: 'CASE CLOSED: badge zero indicted. the ladder is ash.' }
  ],
  verdict: { title: 'LOG 18 — THE LADDER', lines: [
    'The private core burned with the', 'ledger open. Every name on it was',
    'served by morning — badge zero', 'first. The line is finally quiet.'] }
},
{
  id: 'signal-lost', format: 1,
  title: 'SIGNAL LOST', tagline: 'THE DEAD COAST', difficulty: 3,
  story: 'Badge Zero is served — and a whole coastal relay chain goes dark overnight. No breach, no ransom, just silence. Its automated defenses still run with no master, and something has re-lit the dead beacon at the end of the line.',
  map: { theme: 'city' },
  speakers: [
    { id: 'OMNI',  name: 'OmniServe HQ', color: '111,227,255', portrait: { drawn: 'OMNI' } },
    { id: 'CID',   name: 'Cyber Investigations Dept', color: '235,245,255', portrait: { drawn: 'CID' } },
    { id: 'TRACE', name: 'CID tracer analyst', color: '126,226,98', portrait: { drawn: 'TRACE' } },
    { id: 'CORE',  name: 'the beacon', color: '255,230,120', portrait: { drawn: 'CORE' } }
  ],
  levels: [
    { name: 'DEAD HARBOR', tint: '80,200,215', duration: 55, spawnMin: 1.00, spawnMax: 1.65, speed: 0.48, doubles: 0.30, heavies: 0.18, lines: 0.30, colors: 0.35, frags: 0.10, track: 0,
      hint: 'a dead grid — every tap here was left ON PURPOSE',
      story: { title: 'LOG 19 — SIGNAL LOST', lines: [
        'Badge Zero is served. Then a whole', 'coastal relay chain drops off the',
        'map overnight. No breach, no ransom', '— just silence. We go in dark.'] },
      comms: [{ t: 6, s: 'CID', m: 'the coast line is dark. all of it.' },
              { t: 22, s: 'TRACE', m: 'defenses live, operators gone. eerie.' },
              { t: 40, s: 'OMNI', m: 'who taps a line nobody runs?' }],
      caseNote: 'CASE NOTE: the coast went dark on a SCHEDULE. planned silence.' },
    { name: 'GHOST CURRENT', tint: '110,225,170', duration: 55, spawnMin: 0.60, spawnMax: 1.00, speed: 0.58, doubles: 0.60, heavies: 0.06, lines: 0.00, colors: 0.00, frags: 0.10, track: 1, bursts: true,
      hint: 'the current still runs — fast, blind, and full',
      bands: [{ t0: 15, t1: 30, intensity: 1.7 }, { t0: 40, t1: 52, intensity: 1.9 }],
      story: { title: 'LOG 20 — GHOST CURRENT', lines: [
        'The line still carries traffic.', 'Nobody sends it. Nobody reads it.',
        'Ghost packets on a dead current —', 'and something is EATING them.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'traffic with no sender. recorded loops.' },
              { t: 24, s: 'OMNI', m: 'a dead line that will not die.' },
              { t: 44, s: 'CID', m: 'ride it. see where it drains.' }],
      caseNote: 'CASE NOTE: the ghost traffic drains toward the old lighthouse hub.' },
    { name: 'CIPHER SHOALS', tint: '255,190,110', duration: 60, spawnMin: 0.95, spawnMax: 1.50, speed: 0.50, doubles: 0.35, heavies: 0.20, lines: 0.28, colors: 0.45, frags: 0.14, walls: 0.12, track: 2,
      hint: 'shoal water — keyed reefs and sealed pairs, read before you steer',
      beats: [{ t: 26, kind: 'wall' }, { t: 35, kind: 'strip' }, { t: 46, kind: 'wall' }],
      story: { title: 'LOG 21 — THE SHOALS', lines: [
        'The shallows are mined with keyed', 'taps cut years ago — still armed,',
        'still rotating their colors on a', 'dead man\u2019s schedule. Navigate.'] },
      comms: [{ t: 6, s: 'CID', m: 'old keys, still turning. mind the colors.' },
              { t: 20, s: 'TRACE', m: 'these locks predate badge zero. YEARS old.' },
              { t: 38, s: 'OMNI', m: 'then who has been winding them?' }],
      caseNote: 'CASE NOTE: the shoal locks are OLDER than the corruption case.' },
    { name: 'RIPTIDE', tint: '120,160,255', duration: 60, spawnMin: 0.55, spawnMax: 0.92, speed: 0.60, doubles: 0.65, heavies: 0.05, lines: 0.00, colors: 0.00, frags: 0.12, track: 0, bursts: true,
      hint: 'riptide — do not fight the pace, become it',
      bands: [{ t0: 12, t1: 28, intensity: 1.8 }, { t0: 36, t1: 54, intensity: 2.0, mix: { doubles: 0.7 } }],
      story: { title: 'LOG 22 — RIPTIDE', lines: [
        'The drain quickens near the hub.', 'Whole reels of ghost traffic pulled',
        'under at once. Hold the line in the', 'riptide and do not let go.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'flow rate doubled. tripled. keep up.' },
              { t: 30, s: 'CID', m: 'steady hands. it wants you rushed.' }],
      caseNote: 'CASE NOTE: the drain pulls harder the closer we get.' },
    { name: 'THE SHALLOWS', tint: '150,230,120', duration: 65, spawnMin: 0.90, spawnMax: 1.42, speed: 0.52, doubles: 0.35, heavies: 0.22, lines: 0.30, colors: 0.40, frags: 0.16, walls: 0.18, track: 1,
      hint: 'the rail closes in shallow water — plan two moves ahead',
      beats: [{ t: 24, kind: 'wall' }, { t: 40, kind: 'lull', dur: 5 }, { t: 52, kind: 'wall' }],
      story: { title: 'LOG 23 — THE SHALLOWS', lines: [
        'Wrecks everywhere: relays fried by', 'their own walls years ago. Whoever',
        'holds the beacon rehearsed this', 'exact defense — on these bones.'] },
      comms: [{ t: 6, s: 'TRACE', m: 'wall scars on every wreck here.' },
              { t: 20, s: 'CID', m: 'this is a training ground. WAS.' },
              { t: 46, s: 'OMNI', m: 'so the beacon had a teacher once.' }],
      caseNote: 'CASE NOTE: the wrecks are practice targets. YEARS of drills.' },
    { name: 'UNDERTOW', tint: '255,120,140', duration: 70, spawnMin: 0.50, spawnMax: 0.86, speed: 0.63, doubles: 0.65, heavies: 0.12, lines: 0.00, colors: 0.00, frags: 0.18, track: 2, bursts: true,
      hint: 'undertow — the fastest water on the dead coast',
      bands: [{ t0: 14, t1: 34, intensity: 1.8 }, { t0: 46, t1: 64, intensity: 2.2 }],
      story: { title: 'LOG 24 — UNDERTOW', lines: [
        'Under the surface current there is', 'a second one, running the OTHER',
        'way — carrying copies of everything', 'we transmit straight to the hub.'] },
      comms: [{ t: 6, s: 'CID', m: 'it reads us as we ride. shield nothing.' },
              { t: 38, s: 'TRACE', m: 'copies of OUR traffic in the drain.' }],
      caseNote: 'CASE NOTE: the beacon has been listening since relay one.' },
    { name: 'THE NARROWS', tint: '210,140,255', duration: 75, spawnMin: 0.58, spawnMax: 0.98, speed: 0.58, doubles: 0.50, heavies: 0.22, lines: 0.26, colors: 0.40, frags: 0.20, walls: 0.18, track: 0, bursts: true,
      hint: 'the narrows: every trick on the coast, then open water',
      beats: [{ t: 31, kind: 'wall' }, { t: 50, kind: 'wall' }, { t: 62, kind: 'strip' }],
      bands: [{ t0: 34, t1: 48, intensity: 1.9 }],
      story: { title: 'LOG 25 — THE NARROWS', lines: [
        'One channel left. It is everything', 'at once: keys, walls, pairs, ghost',
        'floods. The beacon watches us', 'thread it. It is almost polite.'] },
      comms: [{ t: 6, s: 'OMNI', m: 'it is WAITING for us now.' },
              { t: 26, s: 'TRACE', m: 'signal ahead. clean. an invitation.' },
              { t: 54, s: 'CID', m: 'accept it. weapons hot.' }],
      caseNote: 'CASE NOTE: it let us through. it wanted an audience.' },
    { name: 'THE BEACON', tint: '255,230,120', duration: 50, spawnMin: 0.80, spawnMax: 1.40, speed: 0.55, doubles: 0.35, heavies: 0.18, lines: 0.20, colors: 0.30, frags: 0.14, walls: 0.10, track: 1, boss: true, bossKind: 'spinner',
      hint: 'ride the light — survive every sweep and the beacon burns itself out',
      story: { title: 'LOG 26 — THE LIGHT', lines: [
        'The beacon was built to guide. Left', 'alone with dead orders it guides',
        'still — burning every ship it sees.', 'Stay out of the light. Let it turn.'] },
      comms: [{ t: 4, s: 'CORE', m: 'i kept the light on. where were you?' },
              { t: 16, s: 'CID', m: 'ride the beam, defender. let it spend itself.' }],
      caseNote: 'CASE CLOSED: the light is out. the coast sleeps quiet.' }
  ],
  verdict: { title: 'LOG 27 — LIGHTS OUT', lines: [
    'The beacon burned through its own', 'charge and went dark for good. The',
    'coast came back online by morning.', 'Somewhere, a new case is waiting.'] }
}];
